### ISSUE TITLE
makepkg exited with code: 512

### ISSUE THREAD

**Issue by AladW** [trizen/trizen#10]
`[!] Unable to build 'kglobalaccel-git' - makepkg exited with code: 512`

As far as I understand, a bash script (here makepkg) can have an exit code between 0 and 255:

https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html

Full output: https://gist.github.com/AladW/4e94e47026ecdb527b00705570f65b28
trizen config: https://gist.github.com/AladW/9cb050c9cadbfdf7928fc1271b797ad4

**Comment by trizen** [comment]
Thanks!
