### ISSUE TITLE
Feature Request: --results_sort_order to enable reverse order for search results

### ISSUE THREAD

**Issue by milkmiruku** [trizen/trizen#100]
A reverse option/flag would make things easier for longer search result outputs.

Maybe `--results_sort_order`?

**Comment by trizen** [comment]
An equivalent option is already available:

```console
 trizen -Ss [keywords] --aur-results-sort-by=date --aur-results-sort-order=descending
```

This is due the fact that each configuration key is a valid option when preceded with `--`.

See also: https://github.com/trizen/trizen/issues/58

**Comment by milkmiruku** [comment]
What I'm thinking of is a reverse order where core comes last, i.e., first in terms of scrollback, then, scrolling back, extra is next, then community, then aur, like [pacget](https://github.com/neurobin/pacget);

![image](https://user-images.githubusercontent.com/108225/35477598-5b06098a-03be-11e8-94cf-984b37c2e6bf.png)

**Comment by milkmiruku** [comment]
Awesome, thanks :)

**Comment by milkmiruku** [comment]
Ah, as it works with `trizen perl --flip-repo-results=1 --aur-results-sort-order=descending`, aur results are still printed last, then core, then extra, then community.

**Comment by milkmiruku** [comment]
Ahaha, that's funny, `trizen python --flip-repo-results=1 --aur-results-sort-order=descending` actually works :)

**Comment by milkmiruku** [comment]
Might it be possible to reverse the numbers assigned to the packages too?

**Comment by trizen** [comment]
Hmm... Actually `trizen -a python` is an RPC error: "Too many package results". (https://aur.archlinux.org/rpc.php?v=5&type=search&arg=python)

> Might it be possible to reverse the numbers assigned to the packages too?

Surely. A config option will be added in the next commit.

> [...] aur results are still printed last, then core, then extra, then community.

I will probably rename the config option `flip_repo_results` to `flip_search_results` and reverse the entire list of results such that the aur results are printed first.
