### ISSUE TITLE
No way to query only AUR upgrades

### ISSUE THREAD

**Issue by pierrenaude** [trizen/trizen#103]
One can query main repo upgrades by running 
`trizen -Qu`
but there is no way of querying AUR only upgrades (using -a), e.g.
`trizen -Qua`
This despite the fact that 
`trizen -Sua`
happily identifies AUR upgrades.

**Comment by Skycoder42** [comment]
Very useful feature for "notifier tools" such as octopi as they handle aur updates different from actual repo updates.
