### ISSUE TITLE
Interactive mode: pressing Esc several times starts to echo something similar to "ls"

### ISSUE THREAD

**Issue by milkmiruku** [trizen/trizen#104]
It takes 5 presses in my bash and 6 presses in my zsh. Is this behaviour intended?

**Comment by rafasc** [comment]
That's just your shell trying to autocomplete. It has nothing to do with trizen.
If you type: `echo ESC ESC ESC ESC`, you'll get the same result. You can confirm by checking that `\e` is binded to `complete` with: `bind -p | grep 'complete$'`
You can read a bit more about it [here](https://unix.stackexchange.com/questions/391927/bash-pressing-escape-4-times). The reason why its 4 specifically escapes me, but that's irrelevant for this issue.

**Comment by milkmiruku** [comment]
A-ha, thanks, indeed, in bash, with four presses of Esc, with relatively long gaps between presses, I get:
```
[milk@silver ~]$ bind -p | grep 'complete$'
"\C-i": complete
"\e\e": complete
```
bash isn't my shell _per se_, but aye, this relates to bash readline behaviour, as trizen uses perl-term-readline-gnu.

It turns out this is the same behaviour (4 presses with gaps) for the trizen prompt, I was just pressing Esc too fast, I guess there is a default timeout on pressing Esc in readline like in vim.

**Comment by trizen** [comment]
Not a trizen issue. Closing now.
