### ISSUE TITLE
Can't see any packages from AUR

### ISSUE THREAD

**Issue by pauldotknopf** [trizen/trizen#106]
```
> trizen --debug -Ss font
** GET https://aur.archlinux.org/rpc.php?v=5&type=search&arg=font ==> 500 Can't connect to aur.archlinux.org:433
```

It works with other AUR helpers (same machine, same shell), and I can connect to that domain on a TLS connection.

**Comment by trizen** [comment]
It's a local issue. Maybe you have some proxy settings defined in `env` that are broken? In this case, try setting `lwp_env_proxy` to `0` in trizen's configuration file.

Additionally, try to reinstall the `perl-lwp-protocol-https` package.

**Comment by pauldotknopf** [comment]
This issue happened on an isolated builder server, at the same time it broke locally for me.

It was likely something with aur.archlinux.org.

Regardless, it magically fixed itself. The build server started working as well.
