### ISSUE TITLE
"failed to install" warnings if depends contains a virtual package

### ISSUE THREAD

**Issue by AladW** [trizen/trizen#11]
Virtual packages, i.e. those whose names are only present in a replaces/provides field, give a warning "Unable to install". This does not seem to affect the actual build process.
```
(...)
depends=(python3)
(...)
[!] Unable to install: python3
```
Full output: https://gist.github.com/AladW/cfd607675c0ea4e0cb1f23e1b81e8bc4

Compare to `pacman -T` as used by `makepkg`
```
[archie@bootstrap tmp]$ pacman -T python3
[archie@bootstrap tmp]$ pacman -T python99
python99
```
Or `pacman -S`:
```
[archie@bootstrap tmp]$ sudo pacman -S python3
warning: python-3.6.0-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) python-3.6.0-2

Total Installed Size:  123.39 MiB
Net Upgrade Size:        0.00 MiB

:: Proceed with installation? [Y/n]
```
pacman -Si python output: https://gist.github.com/AladW/f158666ce05afb2f40161cc1ed4c262e
(note: pacman -Si python3 gives an error also)

**Comment by trizen** [comment]
Using `pacman -Sp [...]` (instead of `pacman -Si [...]`) seems to work correctly for virtual packages. This fixes the harmless warning. Thanks!
