### ISSUE TITLE
Advanced package selection prompt

### ISSUE THREAD

**Issue by DragoonAethis** [trizen/trizen#110]
Let's say you have a lot of development AUR packages and you'd like to rebuild them all, except *some*. So you get a list of 50 or so packages, and a prompt to select which ones should be upgraded:

```
  1. package1: ...
  2. package2: ...
  3. package3: ...
 ...
 48. package48: ...
 49. package49: ...
 50. package50: ...

=>> Select packages for upgrade (default: all)
> 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 ...
```

It would be nice if the package picker would also accept something along the lines of this:
- If nothing is entered, picker also defaults to all.
- If `all` is entered, it gets unrolled to a list of all packages to upgrade.
- If `-num` is entered (for example `-38`), that package is removed from the upgrade.

So you could do something like `all -14 -20` to upgrade everything except these two. This would be also very useful while installing packages from groups (to install everything, except 2 or 3 packages you don't want).

**Comment by trizen** [comment]
Good suggestion. I will consider adding this feature in the next release.

Currently we have the option `--ignore="package1 package2 package3 ..."`, which will skip the specified packages from the upgrade list.

**Comment by DragoonAethis** [comment]
Great, thank you!

**Comment by Morganamilo** [comment]
>So you could do something like all -14 -20 to upgrade everything except these two. This would be also very useful while installing packages from groups (to install everything, except 2 or 3 packages you don't want).

I realise this is a bit old but I only just saw it. the `-num` thing is nice but pacman actually supports this feature officially but in the form of `^num`

![image](https://user-images.githubusercontent.com/16593899/37883428-34c78fda-30a2-11e8-83e1-77f779d97ddd.png)

Trizen should probably support this syntax instead/also to conform with pacman.
