### ISSUE TITLE
Long search times

### ISSUE THREAD

**Issue by jnumbers** [trizen/trizen#114]
After installing this package, I've experience search times that take up to 1 minute to complete. This occurs when I use -Ss & -C. Other AUR helpers take a couple of seconds to finish. Is this normal for trizen?

**Comment by trizen** [comment]
> [...] search times that take up to 1 minute to complete. 
> [...] Is this normal for trizen?

It's not.

> Other AUR helpers take a couple of seconds to finish.

A couple of seconds is still quite too much. In normal circumstances, the expected time for a search request with one keyword should be less than 1 second.

```bash
$ time trizen -Ss trizen

[...]

trizen -Ss trizen  0.56s user 0.04s system 79% cpu 0.757 total
```

I specified "one keyword", because the more keywords are used, the longer it takes, as, internally, `trizen` does search narrowing, searching for each keyword, one at a time, narrowing the search results down to only those results that match all the keywords.

For example "`trizen -Ss foo bar`" searches for "foo", then searches for "bar" and displays only the results that contain both "foo" and "bar" (in any order).

In your case, I suspect the SSL verification may be slow, but I could be wrong. To verify that, try:

```console
trizen -Ss trizen --ssl-verify-hostname=0
```

Alternatively, could you, please, install `perl-devel-nytprof` and execute:

```console
perl -d:NYTProf /usr/bin/trizen -Ss trizen
```

and attach the generated output file `nytprof.out` here? This would help me understand exactly which part of the program is slow on your computer. 

Thanks!

**Comment by bkach** [comment]
I'm having the same issue, it takes about a minute.

When executing trizen search in debug mode it hangs on:

`** GET https://aur.archlinux.org/rpc.php?v=5&type=search&arg=trizen ==>`

I tried going to the same address in the browser and it comes back instantly. 

`time trizen -Ss --debug trizen
** GET https://aur.archlinux.org/rpc.php?v=5&type=search&arg=trizen ==> 200 OK (60s)
aur/pacui 1.9.2-1 [4+] [1.2%] [28 Jan 2018]
    Bash script providing advanced Pacman and Trizen/Yay/Yaourt/Pacaur functionality in a simple UI
aur/pacui-git r743.c9edccf-1 [12+] [0.61%] [14 Jan 2018]
    Bash script providing advanced Pacman and Trizen/Yay/Yaourt/Pacaur functionality in a simple UI
aur/tpac 1.0rc2-1 [2+] [1.3%] [31 Jan 2018]
    trizen wrapper to mimic yaourt's search feature
aur/trizen 1:1.44-1 [installed] [152+] [61%] [9 Mar 2018]
    Trizen AUR Package Manager: A lightweight wrapper for AUR.
aur/trizen-git 1.44-1 [4+] [1.5%] [9 Mar 2018]
    Trizen AUR Package Manager: A lightweight wrapper for AUR (-git version).
trizen -Ss --debug trizen  0.27s user 0.03s system 0% cpu 1:00.88 total`

What's interesting is that it always takes exactly one minute - could this be some kind of timeout?

**Comment by bkach** [comment]
Changing my `lwp_timeout` time to 3 makes the wait approx. 3 seconds.

Could the $lwp have something to do with it? Specifically:

` my $response = $lwp->get($url, 'Accept-Encoding' => $accepted_encodings);`

**Comment by trizen** [comment]
It could be a LWP::UserAgent (or Crypt::SSLeay) issue, but I'm unable to reproduce it on my machine, so it's unclear at this point. It could also be something wrong with the AUR servers.

Try this to see if it helps:

```
export HTTPS_VERSION=3; trizen -Ss --debug trizen
```

or:

```
export HTTPS_VERSION=3; trizen -Ss --debug --ssl-verify-hostname=0 trizen
```

Additionally, to determine if it is indeed an issue with the AUR servers, I propose the following simple experiment, using LWP to connect to github.com and aur.archlinux.org, measuring the duration it takes to connect to each server. If it takes equally long in both cases, then it's a LWP-related issue for sure.

Connecting to GitHub:

```
time perl -MLWP::Simple -E 'say length(get("https://github.com/"))'
```

and connecting to AUR:

```
time perl -MLWP::Simple -E 'say length(get("https://aur.archlinux.org/rpc.php?v=5&type=search&arg=trizen"))'
```

**Comment by linuxissuper** [comment]
Unfortunately I have the same problem.
I don't have this problem with paru, if that is any help.
Here are my outputs:

```
export HTTPS_VERSION=3; trizen -Ss --debug trizen
** GET https://aur.archlinux.org/rpc.php?v=5&type=search&arg=trizen ==> 200 OK (61s)
```

```
export HTTPS_VERSION=3; trizen -Ss --debug --ssl-verify-hostname=0 trizen
** GET https://aur.archlinux.org/rpc.php?v=5&type=search&arg=trizen ==> 200 OK (60s)
```

```
time perl -MLWP::Simple -E 'say length(get("https://github.com/"))'
213932
perl -MLWP::Simple -E 'say length(get("https://github.com/"))'  0,13s user 0,02s system 32% cpu 0,452 total
```

```
time perl -MLWP::Simple -E 'say length(get("https://aur.archlinux.org/rpc.php?v=5&type=search&arg=trizen"))'
1256
perl -MLWP::Simple -E   0,12s user 0,02s system 0% cpu 2:09,27 total
```

**Comment by GFdevelop** [comment]
I have another issue that can be related to this, when I clone aur packages with ssh git wait >120 seconds before ask me the password, anyone have this issue?

**Comment by GFdevelop** [comment]
SOLVED: I have disabled `ipv6 on lan` in the modem settings and everything it's working (trizen and `git clone ssh://...`)
