### ISSUE TITLE
Trizen does not update dependencies before updating package

### ISSUE THREAD

**Issue by Kriskras99** [trizen/trizen#121]
This happened with lib32-ldb, it depends lib32-talloc. But it failed building because it needed a higher version of lib32-talloc, which trizen decided to build after building lib32-ldb.

**Comment by trizen** [comment]
Looking at the PKGBUILD of `lib32-ldb`, it does not include a minimum version for `lib32-talloc`. This information needs to be added by the maintainer of `lib32-ldb`.

For example:

```
depends=('lib32-talloc>=2.1.11-1' 'lib32-tevent' 'lib32-tdb' 'lib32-popt' 'ldb')
```
