### ISSUE TITLE
Clean Cache

### ISSUE THREAD

**Issue by vendforce** [trizen/trizen#122]
How to clean Cache ?

pacaur -Scc 
pacman -Scc

trizen -Scc ## nothing

I'm guessing its caching into /var/lib/pacman/sync  directory am I correct ?

So, Doing pacman -Scc clears the cache ? correct  ?

**Comment by trizen** [comment]
`trizen -Scc` is correct:

```
$ trizen -Scc

Cache directory: /tmp/pacman/pkg/
:: Do you want to remove ALL files from cache? [y/N] y
removing all files from cache...

Database directory: /var/lib/pacman/
:: Do you want to remove unused repositories? [Y/n] y
removing unused sync repositories...
:: Removing the content of /tmp/trizen-trizen...
:: Done!
```

It executes `pacman -Scc` then it cleans the clone directory cache.

Do you get any error while executing `trizen -Scc`?
