### ISSUE TITLE
interactive search confused by same name packages

### ISSUE THREAD

**Issue by milkmiruku** [trizen/trizen#125]
Using unofficial repos, entering the number of a package from said repo, trizen will try and install the official  package rather than unofficial.

Example is linux-pf-lts which is in pfkernal as 3.14.77-1 and in aur as 4.9.74-2. 
```
[pfkernel]
Server = http://dl.dropbox.com/u/11734958/$arch
SigLevel = PackageOptional
```

`trizen linux-pf-lts`
gives
```
1 pfkernel/linux-pf-lts
...
11 aur/linux-pf-lts
```
pressing 1 and enter and it tries to install the latter.

**Comment by trizen** [comment]
Good catch. Should be fixed in the above commit. Thanks for reporting.
