### ISSUE TITLE
[suggestion] Add a quick option for --noedit option

### ISSUE THREAD

**Issue by manudroid19** [trizen/trizen#13]
When we want the option --noedit to save time, is too long to write --noedit, so I would suggest a quicker way to do this, like using trizen -S -e or trizen -Se for this. This is not a issue, just a appreciated suggestion. Congrats for your great AUR helper!!!

**Comment by trizen** [comment]
Sorry, but this option will not get added. If you wish, you can create a local alias in `~/.zshrc` or `~/.bashrc`, as:

```bash
alias trizene="trizen --noedit $@"
```

...or (highly not recommended) you can edit the configuration file (`~/.config/trizen/trizen.conf`), changing `noedit => 0`, to `noedit => 1`.
