### ISSUE TITLE
Support `-Syu <pkgname>` like pacman does

### ISSUE THREAD

**Issue by darnir** [trizen/trizen#131]
With pacman, one can issue the following command:

```
$ pacman -Syu new_package
```

and pacman will then update the system _and_ also install the new package. However, trizen doesn't currently support that. Could you please add that?

If I understand it correctly, trizen delegates this to pacman anyways, so you probably just need to pass the rest of the arguments as well

**Comment by omtcvxyz** [comment]
Yes, that seems like a super useful feature I really like about `pacaur`, which I am currently using. I'd be happy to switch to trizen provided it would allow same functionality in this regard, i.e. just using it as a pacman wrapper for both Core and AUR.
