### ISSUE TITLE
Feature request: fish autocomplete

### ISSUE THREAD

**Issue by bitwave** [trizen/trizen#136]
A yaourt/pacman like autocomplete for the fish shell would be awesome.

**Comment by omtcvxyz** [comment]
Oh wow, I literally just went here to request the same thing. As far as my understanding goes, fish completion is based on `man` entries. Therefore, just adding a good manual entry would be enough for the Fish shell.

**Comment by bitwave** [comment]
Yeah you are right, `fish_update_completions` should be enough, if a man page is present.

**Comment by MarcusE1W** [comment]
There is an issue for a man page request already #74 .

I had a look how to create a man page from the README.md. That's quite straight forward.
No idea how to set that up in the system though.
If someone knows that it is probably quite easy to create a man page.

**Comment by trizen** [comment]
Fish completion was [added](https://github.com/trizen/trizen/pull/151) by @LChris314 several months ago (available starting with version 1.49).
