### ISSUE TITLE
Unhelpul output when installing package with unmet dependency

### ISSUE THREAD

**Issue by YamashitaRen** [trizen/trizen#137]
I'm trying to install a package from an unofficial repo having an unmet dependency (dependency is in the AUR but not in any repo).
As expected? the transaction fails but the output is wrong.

How to reproduce : 
Add [archlinuxfr](https://wiki.archlinux.org/index.php/unofficial_user_repositories#archlinuxfr) unofficial repo.
```
$ trizen -S archlinuxfr/discord
:: Package not found: archlinuxfr/discord
```

I would expect trizen to tell me that it can't install discord because of unmet libc++ dependency.

**Comment by trizen** [comment]
This was due to the fact that (unexpectedly):

```console
pacman -Sp archlinuxfr/discord
```

outputs:

```
error: failed to prepare transaction (could not satisfy dependencies)
:: discord: requires libc++
```

**Comment by YamashitaRen** [comment]
Great, thanks !
