### ISSUE TITLE
Pass --force to dependency installations

### ISSUE THREAD

**Issue by aveao** [trizen/trizen#138]
Trizen doesn't seem to pass `--force` to the pacman instances it runs on aur dependency installations, which causes issues with installing some packages.

**Comment by trizen** [comment]
Unfortunately, I can't confirm the issue.

When the `--force` argument is specified to `trizen`, it is always passed to `pacman` , as it can be verified using the `--debug` option:

```console
trizen -S --debug --force <pkgname>
```
