### ISSUE TITLE
When selecting AUR packages to upgrade please allow none

### ISSUE THREAD

**Issue by ArielRosenfeld** [trizen/trizen#141]
When selecting AUR packafes to upgrade please allow none to be upgraded

writing n, N, none or something similar to cancel the upgrade would be good and the keyword/s should be noted in the select packages to upgrade title line

**Comment by trizen** [comment]
Already in `-git` (https://github.com/trizen/trizen/commit/e6dbbbc85b6d39f530999db2a393bc3513fb4f2d). (inserting `0`, `n`, `none`, etc..., will not upgrade anything).

There is also CTRL+C.
