### ISSUE TITLE
Failing sudo password and retrying causes trizen to exit

### ISSUE THREAD

**Issue by SilverMight** [trizen/trizen#142]
If you fail the sudo elevation by entering the wrong password 3 times, you are asked to try again, however doing so causes trizen to give this error:
`
Exiting subroutine via redo at /usr/bin/trizen line 863.
Exiting subroutine via redo at /usr/bin/trizen line 863.
Can't "redo" outside a loop block at /usr/bin/trizen line 863.
`

**Comment by Phoenix1747** [comment]
Same problem here. Not sure why this is closed though, maybe a duplicate? :thinking:

**Comment by trizen** [comment]
Fixed [here](https://github.com/trizen/trizen/commit/e76bdb2915ac170a65c3de33e69e86fcbf4cf5b6).

**Comment by Phoenix1747** [comment]
Oh, nice!
