### ISSUE TITLE
Pull in comments before build starts

### ISSUE THREAD

**Issue by irreleph4nt** [trizen/trizen#143]
Coming from yaourt, one of the distinctive features I am missing is to review AUR comments for packages after having started an upgrade run but before the build process for each package actually starts. This is very helpful especially for larger software which may have lots of dependencies.

"run trizen -C first" or "go check on the web first" are not valid solutions to this as they require me to put in individual package names outside of an upgrade run, which in turn requires me to remember all packages including dependencies that may be build at this point in time. That's just nonsense.

**Comment by trizen** [comment]
This feature is already available by setting the `show_comments` config-option to 1.

Also available as a command-line option:

```console
trizen -S <pkgname> --show-comments
```
