### ISSUE TITLE
Possibility to edit build files even if noedit=1 is active

### ISSUE THREAD

**Issue by snqlby** [trizen/trizen#144]
There was an option for pacaur
`-e, --edit       edit target(s) PKGBUILD and view install script`
It would be great to have similar functional here.
We don't need to edit anything in most cases and `noedit=1` option is active, but sometimes there is a need to edit anything. It would be easy to use `-e` or `--edit` option.
`trizen -S jdk --edit`
`trizen -Syu --edit`
It will explicitly disable 'noedit' option

**Comment by trizen** [comment]
This can be done using: `--noedit=0`.
