### ISSUE TITLE
keep a local copy of aur packages for diff view

### ISSUE THREAD

**Issue by chrunchyjesus** [trizen/trizen#145]
What about keeping a local copy of downloaded AUR packages (pkgbuilds and so on, not the actual software) in the users home directory? This way, we can show a diff view on upgrades and the space required would be minimal.

**Comment by trizen** [comment]
Yes, this is possible by changing the clone directory in the configuration file:

```perl
clone_dir => "$ENV{HOME}/.cache/trizen",
```

Optionally, you can also consider setting the `BUILDDIR` variable in `/etc/makepkg.conf` to a different directory (see: https://github.com/trizen/trizen/issues/140), such that the AUR build files will be stored in the directory specified by `clone_dir`, and the building of the package will take place in a different directory.
