### ISSUE TITLE
Automatically offer to remove orphan packages

### ISSUE THREAD

**Issue by notramo** [trizen/trizen#15]
That would be cool, if trizen would ask to automatically remove packages with -Rs (similarly to yaourt) when running:

trizen -Qtd

**Comment by AladW** [comment]
I'm curious as to why a simple wrapper is not sufficent?
```
#!/bin/sh
trizen -S "$@"
pacman -Qqdt | sudo pacman -Rcs -
```

**Comment by notramo** [comment]
It would be comfortable to use.
