### ISSUE TITLE
Feature request: caching for downloaded git files

### ISSUE THREAD

**Issue by ollisilfvast** [trizen/trizen#150]
Trizen saves files in "/tmp", a directory for temporary files (lost in system restart). This problem is most visible with big git repositories such as "ttf-google-fonts-git". Currently it is saved in "/tmp/trizen-username/ttf-google-fonts-git". Downloading this repository can take a very long time so I propose /home/username/.cache instead at least for git files. Using "/tmp" misses the point of git, i.e. only updating the changes.

**Comment by milkmiruku** [comment]
One can set `clone_dir` in trizen.conf, "Absolute path to the directory where to clone and build packages."
