### ISSUE TITLE
Misinterpretation of package version change as downgrade

### ISSUE THREAD

**Issue by milkmiruku** [trizen/trizen#152]
Mixxx 2.1 just got released. Trizen reported this as a downgrade.

```warning: downgrading package mixxx-git (release.2.1.0.rc1.r56.gb14b2ac01-1 => release.2.1.0.r57.g39a7e5adc-1)```

**Comment by Morganamilo** [comment]
As for as Pacman is concerned that is a downgrade. Maybe contact the AUR maintainer to change how the version is generated or add an epoch or something.

**Comment by trizen** [comment]
Morganamilo is right. This warning is emmited by pacman.
