### ISSUE TITLE
Feature request: trizen -Qu - list (and only list) with upgradable packages, also from AUR

### ISSUE THREAD

**Issue by JuniorJPDJ** [trizen/trizen#160]
I tried to develop update notifier using trizen, but I've not found list of packages suitable for upgrade in trizen switches.
I don't want this switch to make any system changes.

**Comment by trizen** [comment]
There is `trizen -Qua` which displays AUR upgrades (https://github.com/trizen/trizen/commit/fabfe5b9addc82b87b0e0ab98b7490895585703b).

**Comment by JuniorJPDJ** [comment]
You should consider add it to some help somewhere

**Comment by JuniorJPDJ** [comment]
+ trizen -Qu doesn't show both updates, just repo

**Comment by trizen** [comment]
Yes, that is the intended behavior, since `-Qu` is a local query command.

**Comment by JuniorJPDJ** [comment]
Ok, makes sense, thanks
