### ISSUE TITLE
pacman -Ud option local pacman database

### ISSUE THREAD

**Issue by ryanmusante** [trizen/trizen#164]
I read recently about a possible issue that may or may not affect usage. Is this still an issue and how should one mitigate it?

> trizen hasn't addressed the "native pacman" column (in particular its usage of pacman -Ud which may leave your local pacman db in an inconsistent state) since late last year, so it was put under "known issues".

Trizen is listed in the "Discontinued or problematic" category:

https://wiki.archlinux.org/index.php/AUR_helpers#Active

**Comment by AladW** [comment]
Only way to mitigate it is not use this helper. Issue falls on deaf ears.
