### ISSUE TITLE
whipper-git check() permission problem

### ISSUE THREAD

**Issue by milkmiruku** [trizen/trizen#165]
Error message on https://aur.archlinux.org/packages/whipper-git/

It similarly fails with pacaur, though someone in #archlinux advised it works with yay.

Also, apparently the failing test also fails for the whipper package, but it shouldn't break the check(), i.e., it works directly when using makepkg, so apparently this is an AUR helper issue.

**Comment by trizen** [comment]
> [...] it works directly when using makepkg, so apparently this is an AUR helper issue.

I get the same error message with `makepkg` as well, so it's not an AUR helper issue.
