### ISSUE TITLE
[Pacman 5.1] Trizen can't find builded packages from AUR when PKGDEST variable is set

### ISSUE THREAD

**Issue by Rosanna4** [trizen/trizen#166]
After update to Pacman 5.1, makepkg doesn't [create symlink in build directory](https://git.archlinux.org/pacman.git/commit/?id=c0a5884b186c9e0e5c54e8515d0982fcba134073) when PKGDEST is set thus trizen can't find packages it just build. The modified `--packagelist` [option](https://git.archlinux.org/pacman.git/commit/?id=d8591dd3418d55c5736022ef003891fc03b953e0) can be possibly used to overcome this. Alternatively trizen may unset PKGDEST variable before build. See also https://github.com/Jguer/yay/issues/434

**Comment by trizen** [comment]
There is no need to set `PKGDEST` in `/etc/makepkg.conf`, because `trizen` has built-in support for moving a built package.

This feature can be set in the configuration file as:

```perl
movepkg     => 1,
movepkg_dir => '/path/where/to/move/packages',
```

**Comment by Rosanna4** [comment]
`PKGDEST` is still useful for using makepkg manually but it interferes with trizen. Setting `makepkg_command => 'PKGDEST= /usr/bin/makepkg -scf'` can overcome this. Anyway if you think there is no need to protect users from this config issues then feel free to close this. I don't mind keping this for myself.

**Comment by erenfro** [comment]
PKGDEST is good for maintaining your own repository that you build once for, distribute to many, and is standard for makepkg. Please implement fixes around this, such as utilizing makepkg --packagelist to get proper locations of where packages would be found after built to correct this problem.

**Comment by alium** [comment]
Same problem!
i can still use trizen with 
> movepkg     => 1,
> movepkg_dir => '/path/where/to/move/packages',
but i build lot of packages own manually, and i need set PKGDEST in /etc/makepkg.conf, because need all builded package together in one directory.  

before pacman 5.1 works trizen with set PKGDEST in /etc/makepkg.conf normally!

**Comment by Rosanna4** [comment]
@alium you can try setting:
`makepkg_command              => "PKGDEST= /usr/bin/makepkg -scf"`

**Comment by alium** [comment]
> makepkg_command => "PKGDEST= /usr/bin/makepkg -scf"

this really works with pacman 5.1 and trizen. Thanks!! :-D
