### ISSUE TITLE
Recursive resolution of AUR deps not working for python-heatclient

### ISSUE THREAD

**Issue by connesc** [trizen/trizen#169]
When installing [python-heatclient](https://aur.archlinux.org/packages/python-heatclient/), trizen lets `makepkg` install the [python-os-testr](https://aur.archlinux.org/packages/python-os-testr/) dependency. But since it's an AUR package, I get the following error:

```error: target not found: python-os-testr```

Isn't trizen supposed to install python-os-testr from AUR before building python-heatclient?
If so, the issue may be related to check dependencies.

**Comment by AladW** [comment]
`trizen` probably forgets about `checkdepends`.

**Comment by trizen** [comment]
Thanks for reporting! Fixed in the above commit.

**Comment by connesc** [comment]
Awesome, thanks! :+1:
