### ISSUE TITLE
Feature request: multithreading building AUR packages

### ISSUE THREAD

**Issue by editicalu** [trizen/trizen#170]
I often get a lot of AUR updates at the same time. It would be nice if these packages could be built simultaneously.
I understand that it should be impossible to install them all the time, but building and compressing them should be possible.

**Comment by AladW** [comment]
Even if trizen had all information on AUR packages beforehand (which it doesn't, see #89) this would be difficult to implement with no reasonable gain - you can already set `-j4` or similar in `makepkg.conf`. See #127.

**Comment by editicalu** [comment]
It would give a reasonable gain when having several big updates which on their own are single threaded (thinking about all the Jetbrains packages in the AUR). The download and package steps take a huge amount of time (as they have to compress ~500MB per package). These would be faster when done in parallel.

**Comment by Morganamilo** [comment]
You can enable multi threaded compression using the compression options in makepkg.conf.

**Comment by AladW** [comment]
...or you just disable compression altogether since it's quite irrelevant when not hosting packages.

**Comment by Morganamilo** [comment]
```
morganamilo@Octavia ~ % df / /boot -h  
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2       193G  178G  6.8G  97% /
/dev/sda1      1022M   93M  930M  10% /boot
```

Not all of us have huge amount of storage ;)

But yeah you can configure the compression however you like.

**Comment by editicalu** [comment]
Storage ain't no problem here. And when it does `rm /var/cache/pacman/pkg/*` solves that problem. :)
That seems to lower the need for this feature. Will close this for now.
