### ISSUE TITLE
trizen nesting folders inside of each other

### ISSUE THREAD

**Issue by spookykidmm** [trizen/trizen#172]
When attempting to use trizen to fetch aur packages, the various package folders get nested inside of each other instead of being separate directories
![2018-06-13-134505_1366x768_scrot](https://user-images.githubusercontent.com/10724754/41368525-37219ba2-6f10-11e8-8911-6d9649714a81.png)
![2018-06-13-134512_1366x768_scrot](https://user-images.githubusercontent.com/10724754/41368526-3734caa6-6f10-11e8-9a46-4ac2bebd331d.png)
![2018-06-13-134517_1366x768_scrot](https://user-images.githubusercontent.com/10724754/41368527-374b0514-6f10-11e8-841b-bbd2aac192cc.png)

**Comment by trizen** [comment]
Thanks for reporting this issue! Fixed [here](https://github.com/trizen/trizen/commit/5594ec07f5a386f26848f883b470450035ada8e6).
