### ISSUE TITLE
The entry for trizen on archlinux.org's AUR helper page seems out of date

### ISSUE THREAD

**Issue by TomLavenziano** [trizen/trizen#174]
https://wiki.archlinux.org/index.php/AUR_helpers#Active

It has trizen listed as unsafe as well as states that `-G ` is used to disable auto-building, yet the docs state that `-G` simply clones the package to the current repository.

Is the entry still correct?

**Comment by AladW** [comment]
The only thing that's incorrect is your comment.
* it's archlinux.org, not .com
* it's not listed as unsafe
* adding a flag to only clone is exactly what "disable auto building" means

**Comment by SicariusNoctis** [comment]
In a similar vein, `trizen` is listed under "Discontinued/Inactive"... wut

**Comment by TomLavenziano** [comment]
I apologize for being incorrect, when I said it was listed as unsafe I meant that it was in the Discontinued and problematic section. I was trying to understand why since I was deciding which AUR helper to switch to instead of continuing to use yaourt, which I know is regarded as unsafe and is listed along with trizen in that section. Trizen meets my needs yet being grouped together with yaourt made me wary.

**Comment by SicariusNoctis** [comment]
There is this thing that trizen does... differently (controversially):

 - https://github.com/trizen/trizen/commit/ba687bc3c3e306e6f3942e95f825ed6a55d3ad69#commitcomment-26805439
 - https://github.com/trizen/trizen/issues/46

I live with it cuz nothing's broken... yet. :)

**Comment by polygamma** [comment]
@SicariusNoctis - great argument.
