### ISSUE TITLE
installation in a commandline

### ISSUE THREAD

**Issue by seblemaguer** [trizen/trizen#175]
Hello,

I adapted the pacaur install script for trizen in order to have a quick installation using only one command line.

Here is the gist: https://gist.github.com/seblemaguer/ffcb5462e14a2ccbb59b53cc283518c0

Here is the command line:

```sh
curl -s https://gist.githubusercontent.com/seblemaguer/ffcb5462e14a2ccbb59b53cc283518c0/raw/e4c8782e9698ec99397418fc95aa819a7a9c5ee6/install-trizen.sh | sh
```
maybe it would be interesting for other people.

**Comment by trizen** [comment]
There are no AUR dependencies required, so I don't see the need for a "magic" installation script.

It can be just as simply installed with the following command-line:

```console
git clone https://aur.archlinux.org/trizen.git; cd trizen; makepkg -si
```

Thanks anyway!
