### ISSUE TITLE
Missing dependency: fakeroot

### ISSUE THREAD

**Issue by michalmiddleton** [trizen/trizen#176]
Hi, 
Since trizen doesn't like to be ran via sudo/root, I think it's reasonable to make trizen install core/fakeroot as its dependency. 

Thanks for all the work on trizen!

**Comment by trizen** [comment]
To install packages from [AUR](https://wiki.archlinux.org/index.php/Arch_User_Repository#Getting_started), first install the `base-devel` package group and you're good to go.
