### ISSUE TITLE
Print AUR results similarly to repo results

### ISSUE THREAD

**Issue by notramo** [trizen/trizen#18]
What about a config option for printing aur results formatted similarly to pacman's output?
 ```
aur/trizen 207.e40f9cf-1
    Trizen's AUR Package Manager: A lightweight wrapper for AUR.
```
instead of
```
trizen 207.e40f9cf-1 [17+] [0.938161] [29 May 2017] - Trizen's AUR Package Manager: A lightweight wrapper for AUR.
```
If you like the idea, I will try to do it, and open a pull request.

**Comment by trizen** [comment]
Sounds good.

**Comment by notramo** [comment]
I have some ideas how to implement it. Do you have a preferred way of chat?

**Comment by notramo** [comment]
PR #19 opened.
