### ISSUE TITLE
How --local option is supposed to be used?

### ISSUE THREAD

**Issue by Nimamoh** [trizen/trizen#180]
Hello,

I tried to install a local package with trizen like this:

```
$ cd my_package_dir
$ trizen -Sl
```

but nothing happens. I though it would look for the PKGBUILD of the local directory and then resume normal operation just as if it found the package on AUR repo. I don't get how it works.

**Comment by Kr1ss-XD** [comment]
I guess u wouldn't want to use trizen for what you're trying to do you. You'll need to issue 
`makepkg -i`, since you already the PKGBUILD.

`trizen -Sl` needs a package name as argument, creates a subdirectory with that name in your current folder and will _download_ the PKGBUILD there. :wink:

**Comment by trizen** [comment]
Hello,

The `-Sl` option is meant to be used after `-G` or `-Gd`.

For example:

```console
$ trizen -Gd <pkgname>   # clones a package along with its needed AUR dependencies in the current directory
   # here the user can inspect/edit the build files of the cloned packages
$ trizen -Sl <pkgname>   # will build and install <pkgname> along with its AUR dependencies, using the local build files cloned by `-Gd`
```

In general, `trizen -Sl <pkgname>` is equivalent with `trizen --nopull --clone-dir=. <pkgname>`

When the build files for a package do not exist locally, `-Sl` will automatically retrieve them from the AUR.
