### ISSUE TITLE
trizen hides error for missing dependency LWP::Protocol::https

### ISSUE THREAD

**Issue by washtubs** [trizen/trizen#182]
I installed trizen and everything I did just quietly didn't show any aur packages. [reddit thread if you care to see it](https://www.reddit.com/r/archlinux/comments/99ubbq/trizen_not_searching_aur/).

Turns out I needed to turn on `--debug` to expose the following error.

    > trizen --debug -s aurman
    ** GET https://aur.archlinux.org/rpc.php?v=5&type=search&arg=aurman ==> 501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)
    :: No packages found...

So two issues:
1. Make that kind of error not require --debug
2. I guess I'm missing a dependency. Which one is that?

**Comment by trizen** [comment]
`trizen` depends on `perl-lwp-protocol-https`, which is already included in trizen's PKGBUILD.

Make sure to install `trizen` as:

```console
git clone https://aur.archlinux.org/trizen.git
cd trizen
makepkg -si
```

which takes care of all the dependencies.

**Comment by washtubs** [comment]
Note that there are two issues. It's wrong that I had to use `--debug` to make the error visible.

**Comment by trizen** [comment]
Please include here the output that you get by executing the following commands:

```
perl -MData::Dump=pp -MLWP::UserAgent -MLWP::Protocol::https  -E 'say $LWP::Protocol::https::VERSION; pp scalar LWP::Protocol::create("https", LWP::UserAgent->new(ssl_opts => {SSL_version => 'TLSv1_2'}))'
```

and:

```
perl -MLWP::UserAgent -E 'say LWP::UserAgent->new->get("https://aur.archlinux.org/")->status_line'
```

**Comment by washtubs** [comment]
First command

    Can't locate Net/SSLeay.pm in @INC (you may need to install the Net::SSLeay module)) at /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm line 19.
    BEGIN failed--compilation aborted at /usr/share/perl5/vendor_perl/IO/Socket/SSL.pm line 19.
    Compilation failed in require at /usr/share/perl5/vendor_perl/Net/HTTPS.pm line 25.
    Can't locate Net/SSL.pm in @INC (you may need to install the Net::SSL module) (@INC contains: /usr/lib/perl5/5.26/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.26/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.26/core_perl /usr/share/perl5/core_perl) at /usr/share/perl5/vendor_perl/Net/HTTPS.pm line 29.
    Compilation failed in require at /usr/share/perl5/vendor_perl/LWP/Protocol/https.pm line 8.
    Compilation failed in require.
    BEGIN failed--compilation aborted.

Second command

    501 Protocol scheme 'https' is not supported (LWP::Protocol::https not installed)

**Comment by trizen** [comment]
Install the following two packages and try again:

```
sudo pacman -S perl-crypt-ssleay perl-net-ssleay
```

**Comment by washtubs** [comment]
OK, crap, it must have been a transitive dependency, but `pacman -Syu` solved it. 

Sorry, I checked all the immediate deps were up to date, but something else made it work. Thanks for fixing the error message showing up.

FWIW I have `perl-net-ssleay` but not `perl-crypt-ssleay`
