### ISSUE TITLE
Recursive resolution of AUR deps not working for seafile-client

### ISSUE THREAD

**Issue by moritzschaefer** [trizen/trizen#187]
Issue https://github.com/trizen/trizen/issues/169 seems to persist:
`trizen -S seafile-client `

results in

```
Fehler: Ziel nicht gefunden: seafile
==> FEHLER: 'pacman' konnte fehlende Abhängigkeiten nicht installieren.
:: Unable to build seafile-client - makepkg exited with code: 8
```
(seafile is only AUR).

**Comment by trizen** [comment]
Sorry, I cannot reproduce this issue with `trizen-1.53`. 

All the AUR dependencies of `seafile-client` and `seafile` are resolved correctly here.

Full output: https://pastebin.com/HPduSZY7

**Comment by moritzschaefer** [comment]
https://pastebin.com/G8kUNu5ka

**Comment by moritzschaefer** [comment]
Here is the output of my trizen.conf (I did not alter it)
https://pastebin.com/iCCSiKzG
