### ISSUE TITLE
Feature request: Add option to show installed packages not found in the repositories nor AUR

### ISSUE THREAD

**Issue by poinu** [trizen/trizen#188]
Currently when running `trizen -Sua`, trizen tries to detect which are the installed packages to be updated. To do so it checks the _foreign_ packages in pacman (running `pacman -Qm`), and then queries the aurweb RPC interface to check whether those _foreign_ packages can be found in the AUR.

For the packages found, the update process is properly handled. However, packages that are installed (shown in `pacman -Qm`) but no longer in the AUR (nor pacman repos) are silently ignored.

I think it would be very useful to have an option to be able to detect those packages, knowing those have been removed and maybe look for alternatives.

A possible implementation would be comparing the list of results returned by the RPC query with the list returned by `pacman -Qm`, and reporting the missing packages. This could be done [here](https://github.com/trizen/trizen/blob/master/trizen#L2167).

Would do you think?

**Comment by trizen** [comment]
This feature is already implemented via the `show_inexistent` config-option, or the `--show-inexistent` command-line option.

Also, one can use `-Qua` instead of `-Sua` to get the list of packages that need to be updated, along with the list of packages that cannot be found in the AUR:

```console
trizen --show-inexistent -Qua
```

**Comment by poinu** [comment]
Hi, thank you for the hint!

I couldn't find the `--show-inexistent` option in the man page.
Would it make sense to be able to query the _inexistent_ packages without showing the _existent_ packages that need to be updated?

Maybe something in the lines of:
```
trizen -Qm
```
or
```
trizen -Qma
```

**Comment by trizen** [comment]
> I couldn't find the --show-inexistent option in the man page.

The man page states that each config-option is a valid command-line argument when preceded with `--`. You can find documentation for each config-option inside the configuration file.

> Would it make sense to be able to query the inexistent packages without showing the existent packages that need to be updated?

Maybe `-Qma` would make sense, but, in most cases, it would be a useless option, displaying nothing. The warnings generated during `-Sua` and `-Qua` regarding the inexistent packages, I think are enough.

If you want to use this information in a script, or something similar, bellow I included a simple Perl program which displays the foreign programs that do not exist in the AUR. Feel free to adjust it to your needs.

```perl
use 5.014;
use warnings;

use LWP::Simple qw(get);
use JSON qw(from_json);
use URI::Escape qw(uri_escape_utf8);

my $AUR_V = '5';    # current version of AurJson

my $aur_base_url     = 'https://aur.archlinux.org';
my $aur_rpc_base_url = "$aur_base_url/rpc.php";

my %packages = map { split(' ', $_) } `pacman -Qm`;
my @pkgnames = sort keys %packages;

my %exists_in_aur;
@exists_in_aur{@pkgnames} = ();

my @aur_results;

while (@pkgnames) {

    my $url = "$aur_rpc_base_url?v=$AUR_V&type=multiinfo";

    while (length($url) < 4000 and @pkgnames) {
        $url .= '&arg[]=' . uri_escape_utf8(shift(@pkgnames));
    }

    my $multiinfo = from_json(get($url) // die ":: Unable to get info for AUR packages...");

    ref($multiinfo->{results}) eq 'ARRAY' or next;

    push @aur_results, @{$multiinfo->{results}};
}

foreach my $result (@aur_results) {

    ref($result) eq 'HASH' or next;

    $exists_in_aur{$result->{Name}} = 1;
}

foreach my $pkgname (sort keys %exists_in_aur) {
    if (not $exists_in_aur{$pkgname}) {
        say $pkgname;  # does not exist in the AUR
    }
}
```

**Comment by poinu** [comment]
> The man page states that each config-option is a valid command-line argument when preceded with --. You can find documentation for each config-option inside the configuration file.

I didn't notice that either. :sweat_smile: 

Thank you for the code snippet. Currently I don't require this information on any script, my suggestion regarding `trizen -Qma` was purely based on 'completeness' for the existing `-a` modifier.

I agree that `Sua` and `-Qua` can do the job in most situations :)

Cheers

**Comment by poinu** [comment]
Great, thank you! :+1:
