### ISSUE TITLE
Enabling show_comments, disables displaying PKGBUILD

### ISSUE THREAD

**Issue by bag-man** [trizen/trizen#191]
I would like to get trizen to show me the comments and the PKGBUILD before I say yes to building the package. However when I enable ` show_comments` in the config, the PKGBUILD no longer is displayed. 

Another feature that would be really nice is to be able to have a switch to show only the most recent X comments.

**Comment by trizen** [comment]
To always see content of the PKDBUILD (and other build files), make sure to set `show_diff_only => 0` in the configuration file.

Support for displaying the most `n` recent comments has been added [here](https://github.com/trizen/trizen/commit/d6b3dff3c50e7dc64eb182774e01087b7fe155fa). It supports up to 10 comments.

Thanks for the feature request.
