### ISSUE TITLE
Possible to autofill sudo credentials if needed?

### ISSUE THREAD

**Issue by lss4** [trizen/trizen#193]
While AUR explicitly stated the makepkg commands and such must not be run as root, is it possible to allow the user to input sudo credentials beforehand so it can be autofilled whenever asked by pacman?

Although it might be a security risk to save credentials in the memory, I often find myself in need of such a feature like this as when I want to update all AUR packages with no need to modify PKGBUILD, I tend to run it with --noconfirm then forget about it completely, only to find it exited without doing anything because it wasn't able to get sudo credentials since I didn't know when the package completed building. Besides, sudo sessions aren't kept indefinitely, so if the next package took too long to obtain source and finish building, I might need to provide the credentials again, increasing complexity.

Being able to provide sudo credentials for autofill would be nice in case of an unattended scenario. Also, in case of manually installing package that needs an edit to PKGBUILD, it might also be helpful as I can forget about it once it starts building, without having to come back from time to time checking whether the build's completed (and then to provide sudo credentials), if I know the package might take a long while to build.

The good part for trizen is that it keeps the sources downloaded and the packages built for the time being (in /tmp/trizen-username), so I can rerun the command to immediately install the built packages without having to start over. Back then when using yaourt (which doesn't keep downloaded stuffs in case of failure), missing on sudo credentials would mean all the time and bandwidth spent have been wasted.

**Comment by trizen** [comment]
No.
