### ISSUE TITLE
Creating a fish wrapper for trizen -s

### ISSUE THREAD

**Issue by pat-s** [trizen/trizen#195]
I am trying to create a fish wrapper for some `trizen` functions.

When wrapping `trizen -s` I am missing the numbers in the left column and the prompt asking which packages should be installed.
Before I used https://github.com/trizen/trizen/issues/61 which worked.

Looks like this is fish specific? Just started with fish and haven't digged into the details yet. Maybe you have a hint for me.

```fish
function pacsearch "Search all packages"
  trizen -s
end
```

**Comment by trizen** [comment]
The interactive search+install mode is:

```console
% trizen [keywords]
```

I don't use fish myself, but, in order for the interactive mode to work, make sure that stdin and stdout are connected to a tty.

In zsh, the equivalent function would be:

```bash
function pacsearch() {
    trizen $@
}
```

and can be called as:

```console
% pacsearch keywords
```
