### ISSUE TITLE
AUR upgrade stops if a package update fails

### ISSUE THREAD

**Issue by UnsolvedCypher** [trizen/trizen#199]
Currently, if something goes wrong during a package upgrade, the upgrade stops. It would be ideal if the other packages could continue to upgrade regardless of a single package failure.

**Comment by trizen** [comment]
This is already possible by setting the `ask_for_retry` config-option to a `1` (enabled by default).

When a package upgrade fails, there are 2 questions asked:

```
=>> Try again? [y/N]: n
=>> Exit now? [Y/n]: n
```

By answer with `n` to the second question, `trizen` will continue to build/install the remaining packages (if any).

**Comment by UnsolvedCypher** [comment]
My apologies for missing this, I will go ahead and close the issue. Thank you for your quick and helpful response!

**Comment by trizen** [comment]
No problem. Glad you find it helpful.
