### ISSUE TITLE
AUR pkgs upgraded via `-Su` get wrongly installed '--asdeps`

### ISSUE THREAD

**Issue by byte-jra** [trizen/trizen#2]
To reproduce: run `pacman -Qdt`, run `trizen -Su (--devel)`, take note of upgraded pkgs, run `pacman -Qdt` again.

**Comment by trizen** [comment]
Unfortunately, I'm not able to reproduce this issue.

I guess you're either using a version of pacman in another language, or a version of pacman with colors. In the second case, the problem may be fixed in the above commit, but testing is needed.

If everything is ok, you may close the issue.

**Comment by byte-jra** [comment]
Yes, LANG=de_DE.UTF-8 and pacman.conf with "Color" enabled.
But it seems to be fixed now, thanks.
