### ISSUE TITLE
Sudo prompt during unattended updates causes premature exit

### ISSUE THREAD

**Issue by banzr** [trizen/trizen#200]
When trizen is called with the --noconfirm flag and a ;pmg build, such as GCC is compiled, trizen will enter `n` where the password prompt occurs and exits after succcessfully building but re-prompts for sudo rights before install. A more desirable behavior would be for trizen to halt so the user could input their password instead of rebuilding or trying to salvage compiled files from tmp.

**Comment by trizen** [comment]
Simple: if you want interactivity, don't use the `--noconfirm` flag.

**Comment by banzr** [comment]
I understand the rational but a simple check for a password prompt would be extremely convenient for many of trizen's users. I would recommend a non interactive solution but I don't know if a way to ensure sudo rights don't time out after a long build without violating security. Please consider reopening this and simply halt instead of exiting after a password re-prompt. Thank you very much for your time!

**Comment by trizen** [comment]
Actually, there is an way to achieve this behavior:

```console
% trizen --noconfirm --sudo-autorepeat-at-runtime -S [pkgname]
```

It executes `sudo -v` when `trizen` is started, and continues to execute `sudo -v` in the background every 180 seconds, to make sure the sudo rights don't time out.

This ensures that even if the package takes a very long time to build, it will eventually get installed without further interaction (assuming no expected errors happen during build-time and there are no package conflicts during installation).

**Comment by banzr** [comment]
Thanks! I'll investigate your suggestion and test it. I'll confirm soon.

**Comment by lUNuXl** [comment]
In my experience it still asks for password when executing pacman -U...

```
:: Pacman command: /usr/bin/sudo /usr/bin/pacman /tmp/trizen-larry/joplin-appimage/joplin-appimage-1.2.2-1-x86_64.pkg.tar -U --noconfirm
[sudo] password for uwux:
```

**Comment by trizen** [comment]
Try setting `sudo_remove_timestamp => 0,` in configuration file.
