### ISSUE TITLE
trizen cannot install dependency from AUR

### ISSUE THREAD

**Issue by nikitabobko** [trizen/trizen#201]
Try this:
```
trizen -S gcal-notifier-kotlin-gtk
```
And you will get this error:
```
==> Making package: gcal-notifier-kotlin-gtk 2.0.4-1 (Sat 02 Mar 2019 17:51:05 MSK)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: java-gnome-bin
==> ERROR: 'pacman' failed to install missing dependencies.
:: Unable to build gcal-notifier-kotlin-gtk - makepkg exited with code: 8
=>> Try again? [y/N]: 
```
Both [gcal-notifier-kotlin-gtk](https://aur.archlinux.org/packages/gcal-notifier-kotlin-gtk/) and [java-gnome-bin](https://aur.archlinux.org/packages/java-gnome-bin/) are in AUR.

And `yay` installs `gcal-notifier-kotlin-gtk` successfully without any problems

trizen version: 1.57

**Comment by trizen** [comment]
Sorry, but I cannot confirm this issue.

Proof here: https://pastebin.com/2H1SkwyD

**Comment by nikitabobko** [comment]
I discovered that problem with `color_code_dependencies` option in `trizen.conf` file
If this flag set to `1` than everything works. If this flag set to `0` then I have error described above

**Comment by trizen** [comment]
Thanks. Fixed in the above commit. A new version will be tagged soon.

**Comment by nikitabobko** [comment]
Thanks for fast response and bug fix! But I see that you don't use tests. I suggest to use them. Tests won't allow to get such silly bugs in future.
