### ISSUE TITLE
Enhancing building speed by changing compression type

### ISSUE THREAD

**Issue by es20490446e** [trizen/trizen#216]
Be aware of [this](https://gitlab.manjaro.org/applications/pamac/issues/651).

**Comment by trizen** [comment]
The compression type can be changed in `/etc/makepkg.conf`, by setting:

```conf
PKGEXT='.pkg.tar'
```

or:

```conf
PKGEXT='.pkg.tar.gz'
```

**Comment by es20490446e** [comment]
I just read that Arch is planning to default to zstd, so no fix will be needed here.

- [Arch thread](https://lists.archlinux.org/pipermail/arch-dev-public/2019-March/029520.html)
- [Pacman git log](https://git.archlinux.org/svntogit/packages.git/log/?h=packages/pacman)
