### ISSUE TITLE
[SEVERAL BUGS]: Check for all packages that need to be updated is broken!

### ISSUE THREAD

**Issue by seafox** [trizen/trizen#222]
Consider two commands:
```
trizen -Syu --devel --needed
trizen -Quq --devel --needed
```
While the first works as expected, fetching changes from both official repos & AUR...
The second doesn't. BUGS:
1. It seems that `-Qu` can't fetch changes from both officialrepos+AUR in a single command as one would expect. Adding --aur eliminates check for official repos. Doing `-Qu --devel --needed` will not return stuff from AUR... Nor we have any switch combo to **check all repos in one go**.
2. **Quiet** flag is broken. When trying `trizen -Quaq --devel --needed` version labels in packages that needed updates are indeed removed as expected, but there are lines above from the check trace that starting with `::` and don't need updates so erroneously remain unsuppressed.

**Comment by trizen** [comment]
Regarding the `-Q` option:

* `-Q` is for querying the package database and redirects to `pacman`.
* `-Qua` is a special case and displays AUR updates only, as documented.

To query both, use: `trizen -Qu; trizen -Qua`.

Regarding the `--quiet` flag during `--devel --needed`, it's now respected. Thanks!

**Comment by seafox** [comment]
As per trizen own help, its switch `-Qu` is to show **outdated** packages, sir!
![outdated-sir](https://user-images.githubusercontent.com/9025690/74746210-f76ff580-525c-11ea-8262-a854868d192b.png)
Also, see that other helpers respect the absence of --aur exclusively flag and show stuff from AUR without it! Otherwise the behaviour you suggested above is inconsistent with `trizen -Syu --devel --needed` and also would deviate from other helpers by requiring two calls and stitching separate lists that is also inconvinience factor for some uses! Thank you for understanding. Hope you'll fix that or introduce other way to get everything in a single list.
![for-aur-too-1](https://user-images.githubusercontent.com/9025690/74746770-d3f97a80-525d-11ea-93dd-35319f5ccb95.png)
![for-aur-too-2](https://user-images.githubusercontent.com/9025690/74746778-d5c33e00-525d-11ea-9296-a918c815e8c7.png)
