### ISSUE TITLE
Feature request: ignore arguemnt like in pacman

### ISSUE THREAD

**Issue by dvaerum** [trizen/trizen#226]
In `pacman` it is possible to use the argument --ignore to skip a package from being installed, like
```
pacman -Syu --noconfirm --ignore linux --ignore zfs-linux
```
It would be really awesome if you could add this feature to `trizen`, so it is possible to ignore packages form the official/pre-build repo, but also the AUR when updating packages.

Thanks in advance :smiley: 
Btw if the function already exist, I could not find it

**Comment by C0rn3j** [comment]
```
       --ignore='...'
           Space-separated list of packages to ignore during -Su.
```
Reading the man page is hard.

**Comment by dvaerum** [comment]
Yes apparently, but thanks for the help :smile:
