### ISSUE TITLE
Wrong AUR dependency resolving

### ISSUE THREAD

**Issue by notramo** [trizen/trizen#23]
I have installed ```cower-git``` and ```pacaur-git```. When I want to upgrade ```pacaur-git```, trizen wants to install ```cower```, but ```cower-git``` is installed, and it provides```cower```. Pacaur can upgrade only the ```pacaur-git``` package, without installing cower.

**Comment by JJK96** [comment]
This is because the dependency checker does not check if there is a package installed that provides the dependency.
