### ISSUE TITLE
Trizen asks for password after every package

### ISSUE THREAD

**Issue by mozo78** [trizen/trizen#230]
Trizen asks for password after every package. If I have 10 outdated AUR packages, it asks 10 times in a row for a password. I have to keep an eye on terminal and this is very inconvenient. Is there a way trizen to remember the password for the current session?

**Comment by trizen** [comment]
For security reasons, `trizen` (by default) removes the cached sudo credentials before executing `makepkg`.

To disable this security feature, set in configuration-file:

```perl
sudo_remove_timestamp => 0,
```

See also: https://github.com/trizen/trizen/issues/203, https://github.com/trizen/trizen/commit/ce620cb464d5873b1da8968664e685f5c12b8ea5

**Comment by mozo78** [comment]
Thank you!

**Comment by canjbfeeltheesemuffins** [comment]
or use ``--noinstall``
