### ISSUE TITLE
Editing files before install fails validation

### ISSUE THREAD

**Issue by ehaynes99** [trizen/trizen#235]
During installation, trizen prompts to edit files. However, since these edits take place before validating the source files, installation subsequently fails. I'm assuming ignorance on my part, as this would defeat the purpose of allowing editing. Is there a way around this while still validating the tarball?

```
==> Making package: dynamodb 2020_10_12-1 (Fri 19 Feb 2021 04:06:00 PM EST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found config.cfg
  -> Found dynamodb
  -> Found dynamodb.service
  -> Found dynamodb_local_2020-10-12.tar.gz
==> Validating source files with sha256sums...
    config.cfg ... FAILED
    dynamodb ... FAILED
    dynamodb.service ... Passed
    dynamodb_local_2020-10-12.tar.gz ... Passed
==> ERROR: One or more files did not pass the validity check!
:: Unable to build dynamodb - makepkg exited with code: 1
```

**Comment by trizen** [comment]
For now, you have to replace the corresponding hashes (of the edited files) with 'SKIP' in the PKGBUILD file.
