### ISSUE TITLE
[Feature request] Take in 'aur/package_name' as a valid package name

### ISSUE THREAD

**Issue by royjohal** [trizen/trizen#241]
Since the search results coming in from the AUR are displayed in the format `aur/package_name`, it would make sense to be able to provide the same naming format when issuing a command like: `trizen -S aur/package_name`

**Comment by trizen** [comment]
This is already possible (https://github.com/trizen/trizen/commit/c5e720f9ca7c950748cc8b1f82402f8491ecec01).
