### ISSUE TITLE
Add --color and --cachedir

### ISSUE THREAD

**Issue by Hayao0819** [trizen/trizen#246]
Make sure that trizen interprets what Pacman has as standard.

`--cachedir /path/to/cache --color always` is not passed successfully to pacman.

And the arguments for `--cachedir` and `--color` are parsed as package name

At the very least, arguments that trizen can't interpret should be passed to pacman out of order.

I believe that this behavior is wrong. 

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/32128205/156767907-111fe0f5-f41c-410c-88b6-00f95c154e78.png">

**Comment by trizen** [comment]
These arguments are passed to pacman. However, their values need to be provided with `=`.

Example:

```console
trizen -S --cachedir=/var/cache/pacman/pkg --color=always aptpac
```

**Comment by Hayao0819** [comment]
I want to specify without using =. Can you do that?
