### ISSUE TITLE
Not enough space in /tmp when downloading and building big packages.

### ISSUE THREAD

**Issue by Ahmed-Biad-2001** [trizen/trizen#250]
```
.......
/android-studio/opt/android-studio/product-info.json': No space left on device
==> ERROR: A failure occurred in package().
    Aborting...
:: Unable to build android-studio - makepkg exited with code: 4
=>> Try again? [y/N]: n
```

Easy fix: change the clone_dir setting (setting file is `~/.config/trizen/trizen.conf` ) to another directory that is not on tmpfs in `/tmp`.

**Comment by trizen** [comment]
Already changed by default from /tmp to /home. (https://github.com/trizen/trizen/commit/b6530cc2e463eb88b7b98a537ac3251238896482).
