### ISSUE TITLE
[QUESTION] Does trizen empties /sources dir on its own or does it not?

### ISSUE THREAD

**Issue by rado84-github** [trizen/trizen#252]
Some time ago I was told trizen empties the ~/.config/trizen/sources directory on its own once the compiling is completed or canceled but I just found out that it doesn't. I've been using trizen for 3 years now and this directory has never been this large (12 GB), that's why I'm asking this question. If trizen is supposed to automatically empty the sources dir, then it's a bug and I'll change this question to a bug report.

I have an alias to autoclean certain directories after every update, so such dir sizes won't happen anymore.

**Comment by trizen** [comment]
It does not.
