### ISSUE TITLE
Request-URI too large?

### ISSUE THREAD

**Issue by SolarAquarion** [trizen/trizen#28]
** GET https://aur.archlinux.org/rpc.php?v=5&type=multiinfo&arg[]=aconfmgr-git&arg[]=acpi_call-dkms&arg[]=acpitool&arg[]=adapta-gtk-theme-git&arg[]=adjbacklight&arg[]=ahoviewer-git&arg[]=albert&arg[]=ambiance-graphite&arg[]=android-google-repository&arg[]=android-ndk&arg[]=android-sdk&arg[]=android-sdk-platform-tools&arg[]=android-studio&arg[]=android-support-repository&arg[]=apacman&arg[]=apacman-deps&arg[]=apacman-utils&arg[]=appcenter-bzr&arg[]=appmenu-gtk-module-git&arg[]=arc-dark-lxqt-manjaro&arg[]=arc-dark-xfce4-terminal&arg[]=arc-firefox-theme-git&arg[]=arc-icon-theme-git&arg[]=arc-kde-git&arg[]=archdroid-icon-theme&arg[]=archlabs-arc-themes-git&arg[]=archlabs-common-git&arg[]=archlabs-oblogout-themes-git&arg[]=archlabs-openbox-themes-git&arg[]=archlabs-pipemenus-git&arg[]=archlabs-rofi-themes-git&arg[]=archlabs-slimlock-themes-git&arg[]=archlabs-tint2-themes-git&arg[]=archlabs-wallpapers-git&arg[]=archlinux-lxdm-theme-full&arg[]=archlinux-lxqt-theme&arg[]=archlinux-themes-sddm&arg[]=argon&arg[]=argparser&arg[]=argparser-bash&arg[]=argparser-c&arg[]=argparser-doc&arg[]=argparser-java&arg[]=argparser-python&arg[]=artwork-maia&arg[]=asp-git&arg[]=auracle-git&arg[]=aurget&arg[]=aurutils-git&arg[]=auto-auto-complete&arg[]=automounter&arg[]=baka-mplayer-git&arg[]=bamf-ubuntu&arg[]=bash-it-git&arg[]=bash-preexec-git&arg[]=bauerbill&arg[]=bear&arg[]=bemenu-git&arg[]=biicode&arg[]=blackmagic-decklink-sdk&arg[]=bleachbit-git&arg[]=blueshift-git&arg[]=bluez-alsa-git&arg[]=breath-dark-icon-theme&arg[]=breath-icon-theme&arg[]=breath-wallpaper&arg[]=breeze-lxqt&arg[]=breeze-plymouth&arg[]=brisk-menu-git&arg[]=bspwm-git&arg[]=budgie-desktop-git&arg[]=budgie-sntray&arg[]=bunsen-common-git&arg[]=bunsen-exit-ng-git&arg[]=bunsen-openbox-pipemenus-git&arg[]=bunsen-utilities-git&arg[]=burp-backup&arg[]=byobu&arg[]=cairo-infinality-ultimate&arg[]=cardapio-bzr&arg[]=cb-pipemenus-git&arg[]=ccsm-gtk3-git&arg[]=cerbere-git&arg[]=cerebro-git&arg[]=chicken-git&arg[]=choqok-git&arg[]=chromaprint-fftw&arg[]=chrome-shutdown-hook&arg[]=chromium-dev&arg[]=cinnamon-desktop-git&arg[]=cinnamon-menus-git&arg[]=cinnamon-translations-git&arg[]=cl-alexandria&arg[]=cl-ppcre&arg[]=clementine-qt5-git&arg[]=clx-git&arg[]=cmake-extras&arg[]=cmake-modules-elementary-git&arg[]=cmst-git&arg[]=codelite&arg[]=communi-desktop-git&arg[]=compiz-bcop-git&arg[]=compiz-core-git&arg[]=compiz-fusion-plugins-main-git&arg[]=compiz-gtk-git&arg[]=compizconfig-python-git&arg[]=compton-conf-git&arg[]=connman-gtk&arg[]=contemporary-cursors&arg[]=contemporary-icons&arg[]=contemporary-widgets&arg[]=contractor-git&arg[]=corebird-git&arg[]=crowd-greeter&arg[]=crypto%2B%2B-git&arg[]=daala-git&arg[]=dapper&arg[]=dee&arg[]=deepin-nautilus-properties&arg[]=deepin-social-sharing&arg[]=depot-tools-git&arg[]=dex-git&arg[]=dinu-git&arg[]=discord-canary&arg[]=dkms-sorted&arg[]=dmenu-git&arg[]=dmenuv-git&arg[]=dockbarx-gtk3-git&arg[]=dockmanager&arg[]=dotnet-coreclr-git&arg[]=dotnet-host&arg[]=dotnet-runtime-1.1&arg[]=droidcam&arg[]=dwb-git&arg[]=dzen2-xft-xpm-xinerama-git&arg[]=echo-icon-theme-git&arg[]=eidete-bzr&arg[]=elementary-icon-theme-git&arg[]=elementary-wallpapers-git&arg[]=elementary-xfce-icons-git&arg[]=emacs-git&arg[]=emerald-gtk3&arg[]=emojione-picker-git&arg[]=enhanced-ctorrent&arg[]=enki-editor-git&arg[]=evopop-gtk-theme-git&arg[]=evopop-icon-theme&arg[]=exa-git&arg[]=exaile-git&arg[]=faba-icon-theme-git&arg[]=faba-mono-icons-git&arg[]=fbautostart&arg[]=fbdesk&arg[]=fbmenugen&arg[]=fehlstart-git&arg[]=ffmpeg-full-git&arg[]=file-commander-git&arg[]=finch-hg&arg[]=findbrokenpkgs&arg[]=firejail-profiles&arg[]=flatabulous-theme-git&arg[]=flatman-git&arg[]=flatplat-blue-theme&arg[]=flatplat-theme-base16&arg[]=flatwoken-icons-git&arg[]=flite1&arg[]=fluid-git&arg[]=fluxable-newmenu&arg[]=fluxbox-arc-dark&arg[]=fluxbox-style-debian-dark&arg[]=fluxbox-style-greybird&arg[]=fluxbox-style-numix&arg[]=fluxbox-style-solarized-light&arg[]=fluxbox-style-zukitwo&arg[]=fluxbox-styles-mint-x&arg[]=fluxbox-styles-tenr&arg[]=fluxdgmenu&arg[]=fontconfig-infinality-ultimate&arg[]=footnote-bzr&arg[]=forecast-git&arg[]=fpm&arg[]=freetype2-demos-infinality&arg[]=freetype2-infinality-ultimate&arg[]=ftmenu&arg[]=fusion-icon-git&arg[]=fvwm-xdg-menu-git&arg[]=fzf-extras-git&arg[]=fzf-git&arg[]=gala-git&arg[]=gcsvedit&arg[]=gdmenu&arg[]=geany-gtk3-git&arg[]=geany-plugins-gtk3-git&arg[]=general-preprocessor&arg[]=ghetto-skype&arg[]=ghostwriter-git&arg[]=gimp-plugin-resynthesizer-git&arg[]=gis-weather-git&arg[]=git-hub&arg[]=giteye&arg[]=gitodo-git&arg[]=gnome-colors-common-icon-theme&arg[]=gnome-menus2&arg[]=gnome-mpv-git&arg[]=gnome-osx-ii-gtk-theme&arg[]=gnome-osx-ii-nt-gtk-theme&arg[]=gnome-shell-extension-appindicator-git&arg[]=gnome-shell-extension-arch-update&arg[]=gnome-shell-extension-extend-left-box-git&arg[]=gnome-shell-extension-topicons-plus-git&arg[]=gnome-shell-extension-volume-mixer-git&arg[]=gnome-shell-extension-workspaces-to-dock-git&arg[]=goffice0.8&arg[]=goocanvas1&arg[]=google-breakpad-git&arg[]=google-earth&arg[]=google-talkplugin&arg[]=gplugin&arg[]=gpmdp&arg[]=gpodder3&arg[]=gpp&arg[]=granite-git&arg[]=gretl&arg[]=grub-customizer&arg[]=grub-hook&arg[]=grub2-theme-archlinux&arg[]=grub2-theme-vimix-git&arg[]=gsignond&arg[]=gsignond-extension-pantheon-git&arg[]=gsignond-plugin-oauth-git&arg[]=gsignond-plugin-sasl-git&arg[]=gtk-arc-flatabulous-theme-git&arg[]=gtk-theme-arc-flatabulous-git&arg[]=gtk-theme-arc-git&arg[]=gtk-theme-e17gtk-git&arg[]=gtk-theme-elementary-git&arg[]=gtk-theme-iris-dark-git&arg[]=gtk-theme-iris-light-git&arg[]=gtk-theme-numix-sx&arg[]=gtk-theme-solarc-git&arg[]=gtk-theme-united-gnome&arg[]=gtk3-ubuntu&arg[]=gtkd&arg[]=gtkhotkey&arg[]=gtksu-git&arg[]=gummi-gtk3-git&arg[]=haroopad&arg[]=herbstluftwm-git&arg[]=humanity-icon-theme&arg[]=i3-gaps-next-git&arg[]=i3ipc-python-git&arg[]=iat&arg[]=icewm-git&arg[]=ido&arg[]=indicator-application&arg[]=indicator-kdeconnect&arg[]=indicator-notifications&arg[]=indicator-session&arg[]=indicator-sound&arg[]=insync&arg[]=insync-nautilus&arg[]=ipager&arg[]=irccloud&arg[]=irssi-git&arg[]=jdk&arg[]=jdk-devel&arg[]=jgmenu&arg[]=jre&arg[]=jre-devel&arg[]=juffed-qt5-git&arg[]=kagayaki-fonts-base&arg[]=kakoune-git&arg[]=kawaii-player&arg[]=keepassxc-git&arg[]=keybase-git&arg[]=kirigami&arg[]=kitty-git&arg[]=komodo-edit&arg[]=krunner-pass&arg[]=kupfer-git&arg[]=kvantum-qt5&arg[]=kvazaar&arg[]=kvirc-git&arg[]=kwaterfoxhelper&arg[]=lastpass&arg[]=latte-dock-git&arg[]=ld-lsb&arg[]=leiningen&arg[]=lemonbar-xft-git&arg[]=lib32-fontconfig-infinality-ultimate&arg[]=lib32-freetype2-infinality-ultimate&arg[]=lib32-gdbm&arg[]=lib32-python2&arg[]=lib32-tk&arg[]=libaom-git&arg[]=libast&arg[]=libbdplus&arg[]=libbs2b&arg[]=libc%2B%2B&arg[]=libc%2B%2Babi&arg[]=libc%2B%2Bexperimental&arg[]=libcolumbus&arg[]=libcommuni-git&arg[]=libcompizconfig-git&arg[]=libcss-git&arg[]=libcurl-openssl-1.0&arg[]=libdesktop-agnostic-git&arg[]=libdom-git&arg[]=libemf&arg[]=libfm-qt-git&arg[]=libgamma&arg[]=libgee06&arg[]=libgeonames&arg[]=libhubbub-git&arg[]=libilbc&arg[]=libindicate&arg[]=libindicate-gtk2&arg[]=libindicate-gtk3&arg[]=libliri-git&arg[]=liblxqt-git&arg[]=libmfx-git&arg[]=libmygpo-qt5-git&arg[]=libmysofa&arg[]=libnetctlgui&arg[]=libnsbmp-git&arg[]=libnsgif-git&arg[]=libnsutils-git&arg[]=libopenmpt-svn&arg[]=libopenssl-1.0-compat&arg[]=libparserutils-git&arg[]=libpurple-hg&arg[]=libqtxdg-git&arg[]=libqzeitgeist&arg[]=libreoffice-extension-languagetool&arg[]=libspotify&arg[]=libsysstat-git&arg[]=libtermkey-bzr&arg[]=libtimezonemap&arg[]=libunity&arg[]=libunity-misc&arg[]=libutf8proc-git&arg[]=libuvc-git&arg[]=libvterm-bzr&arg[]=libwapcaplet-git&arg[]=libwm-git&arg[]=libwnck%2B-git&arg[]=libxvnc&arg[]=lightdm-mini-greeter&arg[]=lightdm-pantheon-greeter-git&arg[]=lightdm-settings&arg[]=lightdm-slick-greeter&arg[]=lightdm-webkit-theme-aether&arg[]=lightdm-webkit-theme-archlinux&arg[]=lightdm-webkit-theme-google-git&arg[]=lightdm-webkit-theme-petrichor-git&arg[]=lightdm-webkit-theme-sequoia-git&arg[]=lightdm-webkit-theme-tendou&arg[]=lightdm-webkit-theme-userdock&arg[]=lightdm-webkit-theme-wisp&arg[]=lightdm-webkit2-clean&arg[]=lightdm-webkit2-theme-bevel-git&arg[]=lightdm-webkit2-theme-material2-git&arg[]=lighthouse-git&arg[]=lilyterm-git&arg[]=linux-git&arg[]=linux-git-docs&arg[]=linux-git-headers&arg[]=linux-pf-haswell&arg[]=linux-pf-headers&arg[]=linux-pf-preset-default&arg[]=liri-platformtheme-git&arg[]=liri-settings-git&arg[]=liri-shell-git&arg[]=liri-text-git&arg[]=liri-themes-git&arg[]=liri-wallpapers-git&arg[]=liri-wayland-git&arg[]=liri-workspace-git&arg[]=lttng-ust&arg[]=lua-posix&arg[]=lua51-luacheck&arg[]=lua51-luassert&arg[]=lua51-posix&arg[]=luajit-2.1&arg[]=luajit-lgi-git&arg[]=luakit-git&arg[]=lubuntu-artwork&arg[]=lumina-desktop-git&arg[]=lutris&arg[]=luv-icon-theme-git&arg[]=lxqt-about-git&arg[]=lxqt-admin-git&arg[]=lxqt-build-tools-git&arg[]=lxqt-config-git&arg[]=lxqt-connman-applet-git&arg[]=lxqt-globalkeys-git&arg[]=lxqt-notificationd-git&arg[]=lxqt-openssh-askpass-git&arg[]=lxqt-panel-git&arg[]=lxqt-policykit-git&arg[]=lxqt-powermanagement-git&arg[]=lxqt-qtplugin-git&arg[]=lxqt-runner-git&arg[]=lxqt-session-git&arg[]=lxqt-sudo-git&arg[]=ly-git&arg[]=macos-arc-white-theme&arg[]=maia-icon-theme&arg[]=maia-wallpaper&arg[]=mate-indicator-applet&arg[]=mate-panel-sntray&arg[]=mate-snw-plugin&arg[]=mate-tweak-git&arg[]=material-gtk-theme-git&arg[]=mdsplib&arg[]=meliora-openbox-themes&arg[]=menugenerator&arg[]=mikutter&arg[]=mime-archpkg&arg[]=mimeo&arg[]=mist-icon-theme&arg[]=moc-pulse-git&arg[]=modprobed-db&arg[]=moka-icon-theme-git&arg[]=moneydance&arg[]=mp-5-gtk&arg[]=mpc-qt-git&arg[]=mpv-ahjolinna-git&arg[]=msbuild-15-bin&arg[]=mujs&arg[]=mutant&arg[]=mylaunchpad-git&arg[]=ncurses5-compat-libs&arg[]=ne&arg[]=neovim-git&arg[]=neovim-gnome-terminal-wrapper&arg[]=neovim-gtk3-git&arg[]=neovim-qt-git&arg[]=nerd-fonts-git&arg[]=netctlgui-helper&arg[]=netsurf-buildsystem-git&arg[]=netsurf-git&arg[]=ninekey&arg[]=nm-tray-git&arg[]=nocturn&arg[]=nodejs-base16-builder-git&arg[]=nodejs-electron-rebuild&arg[]=nord-xfce-terminal&arg[]=notify-when-done-i3-git&arg[]=notion-git&arg[]=nsgenbind-git&arg[]=numix-gtk-theme-git&arg[]=numix-themes-archblue-git&arg[]=numix-themes-blue-git&arg[]=numix-themes-darkblue-git&arg[]=numix-themes-osx-git&arg[]=nut-multimedia-git&arg[]=nvim-pygtk3-git&arg[]=nvm&arg[]=nylas-mail-bin&arg[]=ob-autostart&arg[]=obconf-qt-git&arg[]=obfilebrowser&arg[]=obmenu-generator&arg[]=obvious-git&arg[]=oomox-git&arg[]=openbox-arc-git&arg[]=openbox-menu-git&arg[]=openbox-shiki-colors-themes&arg[]=openbox-theme-adwaita&arg[]=openbox-theme-arcbox&arg[]=openbox-theme-bluebird-openboxed&arg[]=openbox-theme-redmond-2009&arg[]=openbox-themes-ceti-2&arg[]=openh264&arg[]=osu-lazer-git&arg[]=osx-arc-darker&arg[]=osx-arc-plus&arg[]=osx-arc-shadow&arg[]=osx-arc-white&arg[]=otf-erewhon-kagayaki&arg[]=otf-tex-gyre-kagayaki&arg[]=otter-browser-git&arg[]=ourico&arg[]=owlman&arg[]=oxygen-gtk3-git&arg[]=pac&arg[]=pacgem&arg[]=package-query-git&arg[]=packpack&arg[]=palemoon&arg[]=pantheon-agent-polkit-bzr&arg[]=pantheon-applications-menu-git&arg[]=pantheon-calculator-git&arg[]=pantheon-calendar-git&arg[]=pantheon-camera-git&arg[]=pantheon-dpms-helper-bzr&arg[]=pantheon-files-bzr&arg[]=pantheon-geoclue2-agent-git&arg[]=pantheon-mail-git&arg[]=pantheon-music-git&arg[]=pantheon-notes-bzr&arg[]=pantheon-photos-git&arg[]=pantheon-polkit-agent-git&arg[]=pantheon-print-git&arg[]=pantheon-screenshot-git&arg[]=pantheon-session-bzr&arg[]=pantheon-terminal-git&arg[]=pantheon-videos-git&arg[]=paper-gtk-theme-git&arg[]=paper-icon-theme-git&arg[]=papirus-icon-theme-git&arg[]=pbget&arg[]=pcmanfm-qt-git&arg[]=pdfjs&arg[]=perceptia-git&arg[]=perl-cairo-gobject&arg[]=perl-glib-object-introspection&arg[]=perl-goo-canvas&arg[]=perl-gtk2-unique&arg[]=perl-gtk3&arg[]=perl-gtk3-webkit&arg[]=perl-linux-desktopfiles&arg[]=perl-linux-inotify2&arg[]=perl-term-readline-ttytter&arg[]=perl-test-needsdisplay&arg[]=persepolis-git&arg[]=peruse-git&arg[]=pidgin-hg&arg[]=pkgbuilder&arg[]=plank-bzr&arg[]=plank-theme-arc&arg[]=plasma-pk-updates-git&arg[]=plasma-theme-archlinux&arg[]=plasma5-applet-awesome-widgets&arg[]=plasma5-applets-eventcalendar&arg[]=plasma5-applets-places-widget&arg[]=plasma5-applets-redshift-control-git&arg[]=plasma5-applets-redshift-git&arg[]=plasma5-applets-system-panel&arg[]=plasma5-applets-todolist&arg[]=plasma5-applets-yahoo-weather-widget&arg[]=plasma5-themes-breath&arg[]=plasma5-themes-maia&arg[]=plataro-icons&arg[]=playonlinux5-git&arg[]=plenv&arg[]=plotinus-git&arg[]=plymouth-theme-arch-charge&arg[]=plymouth-theme-arch-logo-gnomish&arg[]=plymouth-theme-ozunity-gnomish&arg[]=pmenu&arg[]=polybar&arg[]=poseidon-browser-git&arg[]=powerline-i3-git&arg[]=ppub&arg[]=preload&arg[]=proot&arg[]=pstoedit-nomagick&arg[]=pulseaudio-ctl&arg[]=pyenv&arg[]=pylibgamma&arg[]=pyrescene-hg&arg[]=python-decorating&arg[]=python-evdev&arg[]=python-iwlib&arg[]=python-mpd2&arg[]=python-pyalsaaudio&arg[]=python-pytaglib&arg[]=python-tweepy&arg[]=python2-beautifulsoup3&arg[]=python2-mygpoclient&arg[]=python2-podcastparser&arg[]=python3-aria2jsonrpc&arg[]=python3-aur&arg[]=python3-colorsysplus&arg[]=python3-memoizedb&arg[]=pywebkitgtk&arg[]=qcomicbook-git&arg[]=qdmenu&arg[]=qmenu_hud-git&arg[]=qmplay2-git&arg[]=qoauth-git&arg[]=qpdfview-bzr&arg[]=qps-git&arg[]=qt-installer-framework&arg[]=qt4-private-headers-dev&arg[]=qt5-accountsservice-git&arg[]=qt5-gsettings-git&arg[]=qt5-styleplugins-git&arg[]=qtcam-git&arg[]=qtcurve-git&arg[]=qterminal-git&arg[]=qtermwidget-git&arg[]=qtile-gnome&arg[]=qtile-python3-git&arg[]=qutebrowser-git&arg[]=qutepart-git&arg[]=rbenv&arg[]=remacs-git&arg[]=remarkable&arg[]=rescepy-git&arg[]=revolt-git&arg[]=rhythmbox-plugin-alternative-toolbar-git&arg[]=rkward-frameworks-git&arg[]=rofi-git&arg[]=rplay&arg[]=rrun&arg[]=rsound&arg[]=ruby-delayer&arg[]=ruby-delayer-deferred&arg[]=ruby-instance_storage&arg[]=ruby-kwalify&arg[]=ruby-memoize&arg[]=ruby-pluggaloid&arg[]=ruby-totoridipjp&arg[]=ruby-twitter-text&arg[]=ruby-typed-array&arg[]=ruby-xz&arg[]=rust-dwm-status&arg[]=rvi-git&arg[]=sandbox&arg[]=scenic-git&arg[]=scratch-text-editor-git&arg[]=screengrab-git&arg[]=screenshot-tool-bzr&arg[]=scudcloud-git&arg[]=sddm-breath-theme&arg[]=sddm-config-editor-git&arg[]=sddm-maia-theme&arg[]=sddm-theme-abstractdark-git&arg[]=sddm-theme-deepin-git&arg[]=shellcheck-git&arg[]=shiki-colors-revival-git&arg[]=shimmer-wallpapers-git&arg[]=shine&arg[]=sidplay2-libs&arg[]=siji-git&arg[]=simple-ccsm&arg[]=skim-git&arg[]=skypeforlinux&arg[]=slap&arg[]=slim-xdm&arg[]=smartgit&arg[]=sndio&arg[]=snorenotify&arg[]=sntray-plugin-translations&arg[]=solar-python&arg[]=solus-icon-theme-git&arg[]=spectrwm-git&arg[]=spotify&arg[]=statnot&arg[]=sublime-text-nightly&arg[]=super-flat-remix-icon-theme&arg[]=sutils-git&arg[]=svp&arg[]=sway-dmenu-desktop&arg[]=swc-git&arg[]=switchboard-git&arg[]=switchboard-plug-a11y-git&arg[]=switchboard-plug-about-git&arg[]=switchboard-plug-applications-git&arg[]=switchboard-plug-bluetooth-git&arg[]=switchboard-plug-datetime-git&arg[]=switchboard-plug-desktop-git&arg[]=switchboard-plug-display-git&arg[]=switchboard-plug-keyboard-git&arg[]=switchboard-plug-locale-git&arg[]=switchboard-plug-mouse-touchpad-git&arg[]=switchboard-plug-network-git&arg[]=switchboard-plug-notifications-git&arg[]=switchboard-plug-parental-controls-git&arg[]=switchboard-plug-power-git&arg[]=switchboard-plug-printers-git&arg[]=switchboard-plug-security-privacy-git&arg[]=switchboard-plug-sharing-git&arg[]=switchboard-plug-sound-git&arg[]=switchboard-plug-user-accounts-git&arg[]=sxhkd-git&arg[]=telepathy-kdeconnect-git&arg[]=temps&arg[]=terminology-git&arg[]=texiteasy&arg[]=the-libs&arg[]=theshell&arg[]=thunarx-python&arg[]=tilix-git&arg[]=tint3-cpp-git&arg[]=tmuxline-git&arg[]=tokyocabinet&arg[]=tomorrow-theme-gedit-git&arg[]=tomorrow-theme-qtcreator-git&arg[]=tomorrow-theme-vim-git&arg[]=topinambour-git&arg[]=topmenu-gtk-git&arg[]=topmenu-gtk3-git&arg[]=topmenu-mozilla-git&arg[]=topmenu-qt-git&arg[]=torrent-file-editor-qt5-git&arg[]=toxygen-git&arg[]=tp_smapi-dkms&arg[]=trackma-git&arg[]=triggerhappy-git&arg[]=trizen&arg[]=ts-bt&arg[]=ts-bugreport&arg[]=ts-polkitagent&arg[]=ts-qtplatform&arg[]=tscheckpass&arg[]=tsscreenlock&arg[]=ttf-alef-ibx&arg[]=ttf-alegreya-ibx&arg[]=ttf-alegreya-sans-ibx&arg[]=ttf-aller&arg[]=ttf-caladea-kagayaki&arg[]=ttf-carlito-kagayaki&arg[]=ttf-contemporary&arg[]=ttf-courier-prime-kagayaki&arg[]=ttf-dejavu-kagayaki&arg[]=ttf-droid-ib&arg[]=ttf-droid-nonlatin-ib&arg[]=ttf-fira-mono-ibx&arg[]=ttf-fira-sans-ibx&arg[]=ttf-font-awesome&arg[]=ttf-hack-ibx&arg[]=ttf-iosevka-ibx&arg[]=ttf-iosevka-pack&arg[]=ttf-ms-win10&arg[]=ttf-ms-win10-japanese&arg[]=ttf-ms-win10-korean&arg[]=ttf-ms-win10-other&arg[]=ttf-ms-win10-sea&arg[]=ttf-ms-win10-thai&arg[]=ttf-ms-win10-zh_cn&arg[]=ttf-ms-win10-zh_tw&arg[]=ttf-noto-fonts-emoji-ib&arg[]=ttf-noto-fonts-ib&arg[]=ttf-pfennig-ibx&arg[]=ttf-playfair-display-ibx&arg[]=ttf-raleway-ibx&arg[]=ttf-roboto-ibx&arg[]=ttf-roboto-mono-ibx&arg[]=ttf-sansation-ibx&arg[]=ttf-signika-family-ib&arg[]=ttf-sinkin-sans-ibx&arg[]=ttf-sorts-mill-goudy-ibx&arg[]=ttf-source-code-pro-ibx&arg[]=ttf-source-sans-pro-ibx&arg[]=ttf-source-serif-pro-ibx&arg[]=ttf-symbola-ib&arg[]=ttf-triod-postnaja-ibx&arg[]=ttf-ubuntu-font-family-ib&arg[]=ttf-umeplus-ibx&arg[]=ttf-unfonts-core-ibx&arg[]=ttf-vlgothic-ibx&arg[]=ttf-vollkorn-ibx&arg[]=ttf-wqy-microhei-ibx&arg[]=ttf-wqy-zenhei-ibx&arg[]=ttf-yanone-kaffeesatz-ibx&arg[]=ttytter&arg[]=tunesviewer&arg[]=turses-git&arg[]=ubuntu-mate-themes&arg[]=udisks&arg[]=ulauncher-git&arg[]=unity-api&arg[]=unity-like-plank-theme&arg[]=update-grub&arg[]=uppity-git&arg[]=upterm&arg[]=uzbl-browser-next-git&arg[]=uzbl-core-next-git&arg[]=uzbl-tabbed-next-git&arg[]=v4l2loopback-dkms-git&arg[]=vala-panel-appmenu-budgie-git&arg[]=vala-panel-appmenu-mate-git&arg[]=vala-panel-appmenu-translations-git&arg[]=vala-panel-appmenu-valapanel-git&arg[]=vala-panel-appmenu-xfce-git&arg[]=vala-panel-extras-battery-git&arg[]=vala-panel-extras-common-git&arg[]=vala-panel-extras-gtop-git&arg[]=vala-panel-extras-volume-git&arg[]=vala-panel-extras-weather-git&arg[]=vala-panel-extras-xkb-flags-git&arg[]=vala-panel-extras-xkb-git&arg[]=vala-panel-git&arg[]=vala-panel-sntray&arg[]=velox-git&arg[]=vertex-icons-git&arg[]=vertex-themes-git&arg[]=vibe-git&arg[]=vim-airline-git&arg[]=vim-airline-gruvbox-git&arg[]=vim-airline-themes-git&arg[]=vim-colorschemes&arg[]=vim-csv-git&arg[]=vim-devicons&arg[]=vim-flagship-git&arg[]=vim-plug-git&arg[]=vim-promptline-git&arg[]=vim-webapi&arg[]=vimix-gtk-themes-git&arg[]=visual-studio-code&arg[]=visual-studio-code-insiders&arg[]=vlc-arc-dark-git&arg[]=vlc-clang-git&arg[]=vncproto&arg[]=vo-aacenc&arg[]=vo-amrwbenc&arg[]=vocal-git&arg[]=vol-git&arg[]=volnoti&arg[]=wallch&arg[]=waterfox-kde-bin&arg[]=way-cooler-git&arg[]=wcmcommander&arg[]=webkitgtk&arg[]=webkitgtk2&arg[]=weechat-git&arg[]=wimlib&arg[]=windowchef-git&arg[]=windows10-icons&arg[]=windows10-tint2rc&arg[]=wine-gaming-nine&arg[]=winetricks-git&arg[]=wingo-git&arg[]=wingpanel-indicator-a11y-git&arg[]=wingpanel-indicator-bluetooth-git&arg[]=wingpanel-indicator-datetime-git&arg[]=wingpanel-indicator-keyboard-git&arg[]=wingpanel-indicator-network-git&arg[]=wingpanel-indicator-notifications-git&arg[]=wingpanel-indicator-power-git&arg[]=wingpanel-indicator-privacy-git&arg[]=wingpanel-indicator-session-git&arg[]=wingpanel-indicator-sound-git&arg[]=wingpanel-standalone-git&arg[]=wld-git&arg[]=wmutils-git&arg[]=wordgrinder-git&arg[]=wpgtk-git&arg[]=wtftw-git&arg[]=xavs&arg[]=xde-ctools&arg[]=xde-helpers&arg[]=xde-icons&arg[]=xde-menu-git&arg[]=xde-session-git&arg[]=xde-styles&arg[]=xde-theme&arg[]=xdg-launch&arg[]=xdg-traymenu&arg[]=xdgmenumaker&arg[]=xdwm&arg[]=xenlism-wildfire-icon-theme-git&arg[]=xfce-slimlock&arg[]=xfce-theme-blackbird-git&arg[]=xfce-theme-cobibird&arg[]=xfce-theme-greybird-git&arg[]=xfce-theme-manager&arg[]=xfce4-composite-editor&arg[]=xfce4-hotcorner-plugin&arg[]=xfce4-panel-sntray&arg[]=xfce4-snw-plugin&arg[]=xfce4-taskbar-plugin&arg[]=xfce4-terminal-base16-colors-git&arg[]=xfce4-terminal-colors-jellyx&arg[]=xfce4-terminal-colors-seoul256&arg[]=xfce4-topmenu-plugin-git&arg[]=xfce4-windowck-plugin&arg[]=xfce4-wmdock-plugin&arg[]=xfdashboard-git&arg[]=xfwm4-theme-breeze&arg[]=xi-core-git&arg[]=xi-gtk-git&arg[]=xombrero-git&arg[]=xonsh-git&arg[]=xorg-xdm-xlogin&arg[]=xpybar&arg[]=xreader&arg[]=xss-lock-git&arg[]=xt7-player-mpv-git&arg[]=xtitle-git&arg[]=xubuntu-artwork&arg[]=xviewer&arg[]=xviewer-plugins&arg[]=xweston-git&arg[]=yabar-git&arg[]=yad&arg[]=yaourt-git&arg[]=yay&arg[]=yltra-flat-icons-git&arg[]=zenbooru&arg[]=zeronet&arg[]=zimg-git&arg[]=zuki-themes-git ==> 414 Request-URI Too Large (1s)
[!] Unable to get info for local packages

**Comment by AladW** [comment]
Simple workaround is to split the URL by 150 arguments. See:

https://bugs.archlinux.org/task/49089
