### ISSUE TITLE
More expressive colors

### ISSUE THREAD

**Issue by pintergreg** [trizen/trizen#30]
I would like to ask more expressive colors in the output like in yaourt. Mainly for the installed flag. It is now bold, but I think it would be nice if the background would be different. When I have a long list of packages it is not so easy to spot if one is installed in trizen output.
Also coloring the version would be great.

Thanks

![kepernyokep_2017-08-10_08-10-48](https://user-images.githubusercontent.com/3854784/29156948-b9d76bc0-7da4-11e7-9875-8f082925d757.png)

**Comment by trizen** [comment]
Thanks for the suggestion!

There is, actually, no need to highlight the "installed" field on a different background. By displaying it in bold green, makes it very easy to spot, as it is the only field with this color.

For illustration, this is how the new output looks now:
![2017-08-27-170123_1920x1080_scrot](https://user-images.githubusercontent.com/614513/29750588-e5f8d744-8b4a-11e7-8a59-53dd992c5e97.png)
