### ISSUE TITLE
makepkg: invalid option '--asroot'

### ISSUE THREAD

**Issue by arcnmx** [trizen/trizen#31]
`makepkg` has lacked the `--asroot` option for year(s?), so this functionality has been broken for quite a while. The option should probably be removed to just let `makepkg` print out its usual root warning. Alternatively it is still possible to work around the limitation by setting the EUID environment variable (ex: `env EUID=1 makepkg`) to bring back the old `--asroot` behaviour.

**Comment by arcnmx** [comment]
A more proper approach would probably be a configuration option to set a user to drop down to when running makepkg.

**Comment by trizen** [comment]
Thanks! For now, `trizen` will simply display the warning produced by `makepkg` when executed with root privileges.

**Comment by pauldotknopf** [comment]
Please don't change this. ```pacaur``` enforced running as root, and it messed with my installation process. I patched ```makepkg``` to allow running as root, only during installation time. It is too anoying to ```su nobody``` everytime you want to build.
