### ISSUE TITLE
provide something similar to checkupdates

### ISSUE THREAD

**Issue by x70b1** [trizen/trizen#33]
pacman has the tool `checkupdates` to show pending updates. 
A similar tool for AUR updates would be nice.

Or is there a solution I haven't seen?

**Comment by trizen** [comment]
What about `trizen -Su --aur`?

**Comment by x70b1** [comment]
Yeah, this is the output I was looking for. 
However, I would like to count how many packages there are. So something like `trizen -Su --aur | wc- l`. But it's interactive. That's why it unfortunately doesn't work.

**Comment by trizen** [comment]
Fixed [here](https://github.com/trizen/trizen/commit/cace0ac05403774536e868f3f8d5c229996de915). When `trizen -Su --aur` is piped in interactive mode, it will just print the packages to be upgraded.

**Comment by x70b1** [comment]
This works well. Awesome, thanks!

**Comment by arngo** [comment]
Can the output be more similar to `checkupdates`, i.e. strip off the numbering and use `->` instead of `==>`? Example:

`1. foo 1.0-1 ==> 2.0-1` would become `foo 1.0-1 -> 2.0-1`

This would help it fit in when listed with `checkupdates` output.
