### ISSUE TITLE
ZSH Completion

### ISSUE THREAD

**Issue by ChuckDaniels87** [trizen/trizen#39]
It would be nice to have ZSH completion for `tizen`. I have some experience with this and if you are interested I can give it a go.

**Comment by trizen** [comment]
That would be awesome.

**Comment by Swedneck** [comment]
Extremely useful, one of the things i miss most from pacaur.

**Comment by trizen** [comment]
Support for zsh completion has been added [here](https://github.com/trizen/trizen/pull/54) by @nicman23.

The feature is available for testing by installing the `trizen-git` package from AUR. If there are no problems, a new version will be tagged soon.

**Comment by ChuckDaniels87** [comment]
Nice work! I have been busy lately. I have taken a look and it seems quite fine.
