### ISSUE TITLE
Feature Request: reviewing confirmations prior to build

### ISSUE THREAD

**Issue by ase1590** [trizen/trizen#42]
One of the nice things from Pacaur was the ability to accept/modify all pkgbuilds prior to build time, that way one could just build all the packages sequentially unattended after accepting all the changes. 

Trizen as far as I can tell requires you to review the pkgbuild, make changes, build, then repeat for every package. Is there a way to change that behavior, or is it planned?

**Comment by trizen** [comment]
I'm afraid this change is not possible without rewriting significant portions of the code.

If you trust a certain a package, along with its dependencies, you can use the`--noconfirm` flag, which will build and install a package without asking any questions.

Alternatively, there is the `-Gd` option (proposed by AladW: https://github.com/trizen/trizen/issues/8), which clones the build files of an AUR package, along with the build files of its needed dependencies.

After the build files are optionally inspected and edited, the package can be built and installed from the local build files by executing the command `trizen -Sl <pkgname>` in the same directory where the `trizen -Gd <pkgname>` command was previously executed.

**Comment by ase1590** [comment]
> I'm afraid this change is not possible without rewriting significant portions of the code.
>If you trust a certain a package, along with its dependencies, you can use the--noconfirm flag, which will build and install a package without asking any questions.

That's what I was afraid of. Okay. good to know, thanks!

**Comment by lervag** [comment]
Although I understand that this may be some work, I just want to add my voice to flag this as a very much desired feature.

In any case: Thanks for your hard work and for this excellent AUR helper!

**Comment by steven-omaha** [comment]
I agree with ase1590 and lervag: This would definetly be a killer-feature. This is what led me to using pacaur in the first place.

**Comment by r00tbox** [comment]
I also would love this feature, it's a feature that let me use pacaur til today (today it broke). i really love this feature it was a game changer for me.

**Comment by Morganamilo** [comment]
Most AUR helpers just need to be rebuilt against the new alpm version. For pacaur you need to rebuild cower.

**Comment by Morganamilo** [comment]
There's plenty of others that support this and are maintained. https://wiki.archlinux.org/index.php/AUR_helpers

**Comment by r00tbox** [comment]
So thin can be closed?

In my case is switched completly to yay.
