### ISSUE TITLE
Uninitialized value $lconfig{"clone_dir"}

### ISSUE THREAD

**Issue by SunCatMC** [trizen/trizen#43]
Just updated to trizen 1:1.29-1, but it fails to launch with the following error:

> $ trizen -h
> 
> Use of uninitialized value $lconfig{"clone_dir"} in -d at /usr/bin/trizen line 241.
> 
> Use of uninitialized value $lconfig{"clone_dir"} in concatenation (.) or string at /usr/bin/trizen line 243.
> 
> :: Unable to create clone directory : No such file or directory at /usr/bin/trizen line 586.

**Comment by mjtullio** [comment]
I have the same issue and output while running trizen 1.29 without root privileges. It works if I run "sudo trizen -h".

**Comment by trizen** [comment]
Thanks for reporting the issue. I should be fixed in the above [commit](https://github.com/trizen/trizen/commit/52d0beab0be2645f3a31af59b76e359ae67a0645). Sorry about that.

Please try `trizen-git` to confirm.

**Comment by mjtullio** [comment]
v1.30, this is the output now

Use of uninitialized value $lconfig{"clone_dir"} in -d at /bin/trizen line 240.
Use of uninitialized value $lconfig{"clone_dir"} in concatenation (.) or string at /bin/trizen line 242.
:: Unable to create clone directory : No such file or directory at /bin/trizen line 585.

**Comment by trizen** [comment]
Looks like the value of `clone_dir`, in the configuration file, is undefined. Setting it to a defined value (for example `clone_dir => "/tmp/trizen",`), should do the trick. 

Fixed in version 1.31 ([here](https://github.com/trizen/trizen/commit/74fd39829db8286034ea9de7d61427be04522c67)).
