### ISSUE TITLE
Why cant I install dropbox-experimental

### ISSUE THREAD

**Issue by deepakjois** [trizen/trizen#44]
```
$ trizen -Su dropbox-experimental
error: target not found: dropbox-experimental
=>> Try again? [y/N]: 
```

It works with pacaur though. Am I missing a flag or something?

**Comment by SunCatMC** [comment]
Works fine with `trizen -S dropbox-experimental`

It looks like `trizen -Su` won't download new specified AUR packages

**Comment by trizen** [comment]
Thanks for reporting this issue. Fixed [here](https://github.com/trizen/trizen/commit/42ca2aa679c345da3a904f9114d035d2e8722e80).
