### ISSUE TITLE
Is there something like --ignore ?

### ISSUE THREAD

**Issue by qutetemp** [trizen/trizen#45]
I have a few local PKGBUILDS which I'd like to manage with my pseudo bash package manager instead of having trizen handle them.

**Comment by trizen** [comment]
Support for ignored packages was added by  @JJK96 in [this](https://github.com/trizen/trizen/pull/40) pull request, which uses the `pacconf` command from the `pacutils` package to detected the ignored packages specified in `/etc/pacman.conf`.

You can specify which packages to be ignored (space separated) in `/etc/pacman.conf` as following:

```
IgnorePkg = package1 package2 package3
```

After installing the `pacutils` optional dependency, `trizen` will ignore those packages during -Su.

**Comment by C0rn3j** [comment]
--ignore doesn't seem to work for me 

https://haste.c0rn3j.com/wenorojuzi.php

**Comment by trizen** [comment]
@C0rn3j try:

```
trizen -Syu --devel --ignore=code-git
```
(notice the equal sign after `--ignore`)

**Comment by Adaephon-GH** [comment]
This still does not seem to work for me with trizen 1.43:

    % trizen -Su --ignore=linux                       
    :: Starting full system upgrade...
    resolving dependencies...
    looking for conflicting packages...
    
    Package (3)         Old Version  New Version  Net Change  Download Size
    
    core/linux          4.15.3-1     4.15.3-2       0.06 MiB      68.78 MiB
    core/linux-headers  4.15.3-1     4.15.3-2       0.00 MiB       8.03 MiB
    extra/nvidia        390.25-10    390.25-11      0.00 MiB       9.01 MiB
    
    Total Download Size:    85.81 MiB
    Total Installed Size:  162.50 MiB
    Net Upgrade Size:        0.06 MiB
    
    :: Proceed with installation? [Y/n]

I also tried using `core/linux` as package specifier as well as ignoring the other two packages, separately and all at once. I have confirmed that `pacutils` is indeed installed as mentioned in #56.
