### ISSUE TITLE
git related error encountered when doing trizen -Su

### ISSUE THREAD

**Issue by deepakjois** [trizen/trizen#47]
Another issue running `trizen -Su` that I just ran into. Running `pacaur -Syu` right after this installed the packages just fine. 

```
deepak@vesuvius:~$ trizen -Su
:: Starting full system upgrade...
 there is nothing to do
 1. firefox-always-nightly: 59.0a1.20171220220602-1 ==> 99.0a1-20
 2. keybase-bin: 1.0.38_20171220214035+a7fe25de8-1 ==> 1.0.38_20171221170044+4c1f9803e-1
 3. trizen: 1:1.32-1 ==> 1:1.33-1

=>> Select packages for upgrade (default: all)
> all
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
:: Package not found: firefox-always-nightly
:: firefox-always-nightly has NOT been upgraded!
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
:: Package not found: keybase-bin
:: keybase-bin has NOT been upgraded!
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
:: Package not found: trizen
:: trizen has NOT been upgraded!
```

**Comment by trizen** [comment]
Using `bleachbit`, right? This tends to leave empty directories in the clone directory, which makes `git` to fail cloning.

However, running `trizen -Sca` should solve the issue.

**Comment by deepakjois** [comment]
Thank you. `trizen -Sca` does solve the issue. So please feel free to close it.

FYI, I am not using `bleachbit`. I also don’t really know which directory you are referring to when you say "clone directory". I am executing all the commands from my home directory.

**Comment by trizen** [comment]
The clone directory is specified in the configuration file of `trizen`, which by default is `/tmp/trizen-$USER`.
