### ISSUE TITLE
Incorrect version transitions displayed for AUR git versions

### ISSUE THREAD

**Issue by dead10ck** [trizen/trizen#48]
The output that compares versions for updates from the AUR seems to display incorrect versions.

```sh
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
 1. alacritty-git: 0.1.0.653.g9bdac6b-1 ==> 0.1.0.569.g4e9b1c5-1
 2. antigen-git: v2.2.2.r2.gd04bff1-1 ==> v2.2.2.r2.gd04bff1-1
 3. chrome-gnome-shell-git: 9.r34.g5463caa-1 ==> 9.r0.g35851c7-1
 4. flamegraph-git: r273.a8d807a-1 ==> r174.4d7e64e-1
 5. kafkacat-git: r201.aae2799-1 ==> r103.7116f28-1
 6. librdkafka-git: r2357.cb6f08c-1 ==> r2092.4d2aea3-1

=>> Select packages for upgrade (default: all)
> 
HEAD is now at 437ebd6 move makedepends
Already up to date.
:: Package alacritty-git is installed and up-to-date -- skipping
HEAD is now at 505c759 Update version
Already up to date.
:: Package antigen-git is installed and up-to-date -- skipping
HEAD is now at b2af879 Update to 9
Already up to date.
:: Package chrome-gnome-shell-git is installed and up-to-date -- skipping
HEAD is now at 6aac618 Init
Already up to date.
:: Package flamegraph-git is installed and up-to-date -- skipping
HEAD is now at dc4f47d pkgbuild: add yajl dependency
Already up to date.
:: Package kafkacat-git is installed and up-to-date -- skipping
HEAD is now at 5c2baa2 bump version
Already up to date.
:: Package librdkafka-git is installed and up-to-date -- skipping
```

In particular, options 1, 3, 4, 5, and 6 all display going from a newer version to an older version, and then when it attempts to update them, it shows that they are up-to-date.

**Comment by trizen** [comment]
Not really an issue. You seem to be using the `--devel` flag in combination with the `--needed` flag.

The `--devel` option will simply display all the VCS packages during `-Su`, allowing the user to select which ones to update. The version on the left is the local version, and the version on the right is the AUR version.

The `--needed` flag compares the local version against the AUR version and does not install a package if the local version is greater or equal to the AUR version. For VCS packages, this is often incorrect.

Trying again without the `--needed` flag, should update all the VCS packages correctly.

In general, you don't really want to specify the `--devel` at each `-Su` operation.

**Comment by dead10ck** [comment]
Without `--devel`, it won't update my `-git` packages. So yes, I do need it with every `-Su`. Also, without `--needed`, it will show me all files in the package and recompile every single time, even when there are no updates since the last installed version. I think what `--needed` should do for devel packages is not check the AUR version, but do a git pull, get the version from `pkgver()` and compare the current version with that. I think this is what `pacaur` does.

**Comment by trizen** [comment]
`git pull` would not be helpful here, as the version of `pkgver()` will be the same as that from the AUR, unless we first execute `makepkg` and start the building process, which will only then update the version in the PKGBUILD, as far as I know.

For now, I'm thinking about disabling the behavior of the `--needed` option for VCS packages.

**Comment by dead10ck** [comment]
Sorry, I meant `git pull` on the package's source, not the Arch package. Sorry, I'm only vaguely familiar with the gritty details of how this is implemented, but from a user perspective, it seems rebuilding the whole package *before* checking for whether there exists an update is time-consuming and unnecessary. This isn't meant as a criticism, but other AUR helpers I've used don't seem to have an issue with this, so it must be possible. Disabling `--needed` seems like a bit of an extreme answer to this issue.

**Comment by trizen** [comment]
> Sorry, I meant git pull on the package's source

I don't think I want to go down that rabbit hole. For large code sources, like `linux-git` this would take quite a bit of time, to say the least.

> Disabling --needed seems like a bit of an extreme answer to this issue.

Not at all. It actually makes sense, because since we cannot (yet) prove that an installed VCS package is up-to-date, the best thing that we can do, is to assume the opposite to be true.

**Comment by dead10ck** [comment]
> I don't think I want to go down that rabbit hole. For large code sources, like linux-git this would take quite a bit of time, to say the least.

Don't you have to do this anyway when updating? And doesn't it only happen when the user specifies `--devel`? I don't see how this is an issue that's specific to `--needed`.

> Not at all. It actually makes sense, because since we cannot (yet) prove that an installed VCS package is up-to-date, the best thing that we can do, is to assume the opposite to be true.

Okay, well, it's your software, so that is your prerogative. I'm giving you feedback that could improve your user experience, but you don't seem very open to discussion, so I'll just leave this conversation here. Best of luck!

**Comment by trizen** [comment]
> Don't you have to do this anyway when updating?

True, but what if a user wants to update only a couple of VCS packages during `-Su --devel`, and there are, let's say, more than 10 VCS packages installed. Wouldn't this be a waste of time cloning the source code of each package, just to check the version? I think there must be better ways for doing this, but I don't see one at a moment.

> I don't see how this is an issue that's specific to --needed.

As explained in my first comment, the `--needed` flag checks the local version of a package against the AUR version of the same package. Because `makepkg` updates the version of a VCS package when building the package, the installed VCS package will often have a higher local version than the one that is in AUR.

The rational for disabling the `--needed` flag for VCS packages (ONLY) is exactly because of that.

I appreciate the feedback and the initiative in helping to improve the user experience of users of this software.

Best wishes!

**Comment by rmarquis** [comment]
My 2 cents: it's actually only really slow if the previous cloned source is discarded, but otherwise quite usable as only the source diff would be pulled. However, pacaur works in various stages rather than calling makepkg in a single pass, so the idea might not be totally relevant here.

**Comment by eli-schwartz** [comment]
> As explained in my first comment, the --needed flag checks the local version of a package against the AUR version of the same package. Because makepkg updates the version of a VCS package when building the package, the installed VCS package will often have a higher local version than the one that is in AUR.

This is markedly different from what pacman uses the `--needed` flag for. If you are going to wrap pacman's options, then *do so*.  If you are going to add incompatible methodologies to your handling of AUR packages, please use a different flag that is unique to trizen.

pacman has the concept of 5 different transaction types.
- Install
- Reinstall
- Upgrade
- Downgrade
- Remove

The `--needed` flag causes pacman to remove packages from the transaction list, if they fall under the category of *Reinstall*, and Reinstall *only*.
Also, pacman strictly defines `-Suu` as the way to downgrade packages, without the doubled `-u` option it will warn you that your version is newer and skip the package. If trizen is doing something different for AUR packages, I would consider that an unintuitive design flaw.

For what it's worth, AUR helpers as a rule either don't handle VCS packages at all, or use the --devel flag to indicate that VCS packages should *always* be considered to "have a new version", at least until you check how the pkgver() function updates it. So I think you made the right call.
