### ISSUE TITLE
Feature Request: Others Languages

### ISSUE THREAD

**Issue by beatussum** [trizen/trizen#49]
Can you add the possibility to have several languages instead of one.
Thanks for your project very active and useful !

PS: My english can incorrect because I'm french :smile:

**Comment by trizen** [comment]
Multi-language support has been proposed before (see https://github.com/trizen/trizen/issues/26), but I don't know if this will happen in the near future, unfortunately.

If someone has experience in this area and would like to contribute, pull requests are always very welcomed and I would be happy to assist in the process.

Thanks for appreciation. :+1:

**Comment by MBasicComputing** [comment]
This someone will not be me because I don't know too much the Perl... 😅

**Comment by Swedneck** [comment]
If this gets implemented i'm willing to help translate to Swedish. Can't promise 100% translations however.

**Comment by noomly** [comment]
I could also help to translate in French.

**Comment by sere** [comment]
I could help to translate in Italian

**Comment by btd1337** [comment]
I could help to translate in Portuguese

**Comment by Phoenix1747** [comment]
Is it really worth the effort? I mean the community would help, but Trizen doesn't consist of that many strings :thinking:

**Comment by btd1337** [comment]
@trizen See this: https://perldoc.perl.org/I18N/Langinfo.html

**Comment by beatussum** [comment]
@trizen Maybe you could use the _gettext tools_. It's compatible with **Perl**.

**Comment by trizen** [comment]
It's decided: this will never happen. Too much complexity for too little benefit.
