### ISSUE TITLE
Feature Request: .pacnew management

### ISSUE THREAD

**Issue by Ennoia11** [trizen/trizen#50]
I'm switching from yaourt to trizen and the only feature I'm missing is -C ie pacnew and pacorig files management. Could you please implement this feature ?
Dont ask for perl code, I'm hardly a bash programmer but I can do some beta testing if you need it.

**Comment by trizen** [comment]
Hi. Could you, please, explain concretely what this feature should do? Thanks!

**Comment by Ennoia11** [comment]
First, list them. Something like :
```
0 .pacorig found
0 .pacnew found
0 .pacsave found
0 files are orphans
```
Second, propose to edit, replace, suppress the files one by one using vimdiff or whatever existing CLI diff editor. Some thing like :
```
1 12/23/17 20:09:47  /etc/group.pacnew
==> Enter n° :  1
==> .pacnew: /etc/group
==> Action: [E]dit, [R]eplace, [S]uppress, [C]ontinue (default), [A]bort ?
```
When you're done editing, ask the question again to suppress the pacnew.
HTH

**Comment by brianbuccola** [comment]
Why not just use `pacdiff` for this? You could even do something like

    alias updpkgs='trizen -Syu && sudo pacdiff'

in your shell config, then just run `updpkgs` to update packages and resolve any potential pacdiffs.

**Comment by Ennoia11** [comment]
Because I didn't know it!!
(Habits! Sight)
I can work with that and as a bonus it's part of pacman package. So unless you want to enhance this feature it's OK for me. Thanks for answering.

**Comment by trizen** [comment]
Using `pacdiff` is definitely a good solution. There is no need to reinvent the wheel. Closing this now...
