### ISSUE TITLE
Trizen fails to honour IgnorePkg in pacman.conf 

### ISSUE THREAD

**Issue by drfarmerdave** [trizen/trizen#51]
Trizen updated AUR packages that I have listed in IgnorePkg in /etc/pacman.conf
Is this expected behaviour?

**Comment by trizen** [comment]
Hi. Support for ignored packages is provided by `pacutils`, so make sure to have that package installed.

**Comment by drfarmerdave** [comment]
Thanks, I'd never come across this issue previously.
