### ISSUE TITLE
Show ignored package upgrades

### ISSUE THREAD

**Issue by Bobo1239** [trizen/trizen#52]
#40 added support for ignoring packages from `pacman.conf`. I'd be nice if there was a warning when a newer version is available but the package is ignored. That's the normal behaviour of `pacman` and also of the now discontinued `pacaur`.
example (pacman/pacaur):
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
 sublime-text is up to date
:: Starting full system upgrade...
warning: firefox: ignoring package upgrade (56.0.2-1 => 57.0.2-1)
 there is nothing to do
:: Starting AUR upgrade...
:: freecad-git: ignoring package upgrade (1:0.17pre.r6003.ge7d4296b2-1 => latest)
:: lmms-qt5-git: ignoring package upgrade (1.2.0.rc3.r57.ge5db27542-1 => latest)
:: renderdoc-git: ignoring package upgrade (r1.019b307-1 => latest)
:: unity-editor: ignoring package upgrade (1:2017.2.0f3+20171013-4 => 1:2017.2.0f3+20171013-5)
```

**Comment by trizen** [comment]
Added [here](https://github.com/trizen/trizen/commit/3a3df3142b35eac06de7c38858faa92ff8505779). Thanks for the suggestion.

**Comment by Bobo1239** [comment]
That was quick ;)
Thanks and enjoy the holidays!

**Comment by trizen** [comment]
Thanks! You too. :+1:
