### ISSUE TITLE
[Manjaro's Pacman] warning: config /etc/pacman.conf line 20: unknown option 'SyncFirst'

### ISSUE THREAD

**Issue by mjtullio** [trizen/trizen#53]
I got the title warning output when running trizen over Manjaro. The line 20 of the default pacman.conf is: 

```
# If upgrades are available for these packages they will be asked for first
SyncFirst = manjaro-system archlinux-keyring manjaro-keyring

```
Then trizen works fine, it's just that I get that warning and I'd like to let you know about it.

**Comment by trizen** [comment]
This warning comes from `pacconf`. Fixed [here](https://github.com/trizen/trizen/commit/1cce558cd3c72c810ef25a7c0edbd5db9d6ac47f), by redirecting the standard error to `/dev/null` when `pacconf` is executed. 

Thanks for reporting.
