### ISSUE TITLE
trizen creates file &STDERR

### ISSUE THREAD

**Issue by x70b1** [trizen/trizen#55]
Hi trizen

Under special circumstances trizen creates the file `~/&STDERR`. It's empty, but trizen touch it. That's why it is in my home dir. I used `lsof` to verify it.

I saw it the first time after that change: https://github.com/trizen/trizen/issues/33

But now the complicated part. I don't know under what circumstances the file will be called. When I run the script `updates.sh` with the bash I don't have this behavior. I only have it if the script is called via Polybar in a certain interval. Polybar starts in the i3wm autostart.

Maybe you have an idea. Currently I delete the file with `rm` at the end of the script. So she's always gone. 

**updates.sh** is is executed in an interval of 60 seconds:
```
#!/bin/sh

updates_arch=$(checkupdates | wc -l)

if ! updates_aur=$(trizen --really-quiet -Su --aur | wc -l); then
    updates_aur=0
fi

updates=$(("$updates_arch" + "$updates_aur"))

if [ "$updates" -gt 0 ]; then
    echo "# $updates"
else
    echo ""
fi
```

**Comment by trizen** [comment]
Hi. Thanks for reporting this. 

The issue is caused by the `--really-quiet` argument, which is no longer documented and will be removed in the next release, as it was never useful anyway.

To fix this, you may want to change the command:
```
trizen --really-quiet -Su --aur | wc -l
```
to:
```
trizen --quiet -Su --aur | wc -l
```

The argument `--really-quiet` made `trizen` to not output anything at all, which is basically equivalent with `trizen &> /dev/null`, but with stdin enabled.

On the other hand, the `--quiet` argument will only prevent `trizen` from displaying warnings.

**Comment by x70b1** [comment]
Thanks man! I try it.

**Comment by x70b1** [comment]
Unfortunately, the date is still being created.

**Comment by trizen** [comment]
Hmm... I can't reproduce the issue. Maybe the file is created by some other tool?

**Comment by x70b1** [comment]
No change with `trizen -Su --aur | wc -l`. 
I was afraid of that. The direct call does not cause any problems. But with Polybar there is this problem. 

I run `lsof -r 1 '/home/x70b1/&STDERR'`. And sometimes i can see this:
```
=======
=======
COMMAND  PID  USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
trizen  3451 x70b1    3w   REG  254,0        0 11143906 /home/x70b1/&STDERR
=======
=======
=======
```

**Comment by x70b1** [comment]
If I use `trizen | wc -l` the file isnt created. (Its a stupid example because this prints 33 lines and no updates)

But this would mean the problem could be in the code of `-Su --aur`.

**Comment by trizen** [comment]
Please try the latest commit to see if it fixes the issue. It's a little bit strange. Probably is a Perl issue?
 Because `trizen` does not create this file explicitly.

**Comment by x70b1** [comment]
Unfortunately no improvement. 

Okay, than we cant fix it. I delete this file at the end of my script. I know its tricky and I cant find out what is wrong there. Thanks for your help!

**Comment by rafasc** [comment]
I am having the same issue with a systemd unit.
It's a one-shot unit that runs a script similar to the original script mentioned in this issue.

**Comment by x70b1** [comment]
Could you give some more information about that? Maybe we find something. Could you post your unit file?

**Comment by rafasc** [comment]
In my setup I have this service run periodically to create a notification if there is updates available. Not really relevant for the bug in question but here is a minimal working example:

`~/.config/systemd/user/pacman_notification.service`
``` INI
[Unit]
Description=Check System Updates

[Service]
Type=oneshot
ExecStart=/path/to/script/pacman_notification.sh

[Install]
WantedBy=default.target
```
`pacman_notification.sh`
``` Shell
#!/usr/bin/bash
aur_upd=$(trizen --quiet -Su --aur)
#do something with variable... notification, alarm, whatever
```
`systemctl --user start pacman_notification.service`
This will run the script once and a file named '&STDERR' should appear on the user's home.

**Comment by x70b1** [comment]
Thank you! I can't see many things in common. 

The only thing is that we're both using the same `trizen` command.
