### ISSUE TITLE
ignores IgnorePkg option in /etc/pacman.conf

### ISSUE THREAD

**Issue by 4001982248998** [trizen/trizen#56]
trizen does not honour settings to ignore certain packages, making unattended package maintenance impossible.

These are examples from ```/etc/pacman.conf```:

``` ini 
[options]
# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
IgnorePkg   = linux
IgnorePkg   = icaclient        # "SSL-Error 47"
IgnorePkg   = gstreamer0.10-base
IgnorePkg   = gstreamer0.10
IgnorePkg   = imapsync         # compile takes hours, then fails
IgnorePkg   = lib32-freetype2  # https://bbs.archlinux.org/viewtopic.php?id=230675
#IgnoreGroup =
#NoUpgrade =
#NoExtract =
```

**Comment by trizen** [comment]
Hi. Support for ignored packages is provided by  installing the `pacutils` package.

**Comment by portaloffreedom** [comment]
I installed the `pacutils` package and still the IgnorePkg variable is not respected for me

example:
```ini
[options]
# Pacman won't upgrade packages listed in IgnorePkg and members of IgnoreGroup
IgnorePkg   = ignition-math,sdformat
```

**Comment by trizen** [comment]
The ignored packages must be separated with whitespace.

Example:
```ini
IgnorePkg   = ignition-math sdformat
```

See also: https://github.com/trizen/trizen/issues/45
