### ISSUE TITLE
Inconsistent use of pacman_command and leftover options

### ISSUE THREAD

**Issue by popsUlfr** [trizen/trizen#57]
Hello,

first I'd like to say that this is a terrific AUR helper, so thanks for the efforts!

I noticed that the `pacman_command` config option isn't being consistently used throughout the code and in certain parts a hardcoded path `/usr/bin/pacman` is in its place : 

In `is_available_in_pacman_repo()`:
https://github.com/trizen/trizen/blob/953c1fdbc16077fa2e4464a43b4d478820b6d812/trizen#L742
In `package_is_installed()`:
https://github.com/trizen/trizen/blob/953c1fdbc16077fa2e4464a43b4d478820b6d812/trizen#L786
In `install_package()`:
https://github.com/trizen/trizen/blob/953c1fdbc16077fa2e4464a43b4d478820b6d812/trizen#L1555
In `update_local_packages()`:
https://github.com/trizen/trizen/blob/953c1fdbc16077fa2e4464a43b4d478820b6d812/trizen#L1719

This creates a confusing situation when using the pacman `--root` option for instance to manage a separate arch install like a clean chroot. There's the `get_pacman_arguments()` logic  used with `execute_pacman_command()` which correctly keeps these leftover options during a search but during sync the local system is used instead.

using ffmpeg-full as example, the package is already installed on the "host" system, `pacman_local_dir` is set to `/srv/archbuild/chroot64/root/var/lib/pacman/local` :
```sh
$ trizen -Ss ffmpeg-full
:: Pacman command: /usr/bin/pacman -Ss ffmpeg-full
** GET https://aur.archlinux.org/rpc.php?v=5&type=search&arg=ffmpeg-full ==> 200 OK (1s)
aur/ffmpeg-full 3.4.1-1 [installed] [63+] [0.92%] [23 Dec 2017]
    Record, convert and stream audio and video (all possible features including nvenc, qsv and libfdk-aac)
```
```sh
$ trizen --root=/srv/archbuild/chroot64/root -Ss ffmpeg-full
:: Pacman command: /usr/bin/pacman -Ss --root=/srv/archbuild/chroot64/root ffmpeg-full
** GET https://aur.archlinux.org/rpc.php?v=5&type=search&arg=ffmpeg-full ==> 200 OK
aur/ffmpeg-full 3.4.1-1 [63+] [0.92%] [23 Dec 2017]
    Record, convert and stream audio and video (all possible features including nvenc, qsv and libfdk-aac)
```

So for instance fetching the build files and all aur dependencies is not in accordance with the `--root` option. While the dependencies are missing in the chroot they are there on the host therefore trizen doesn't fetch anything except for the ffmpeg-full build files.

Due to this line it seems :
In `install_package()`:
https://github.com/trizen/trizen/blob/953c1fdbc16077fa2e4464a43b4d478820b6d812/trizen#L1555

It would be more consistent if the `pacman_command` option and the leftover args logic could be used anywhere pacman is called though I'm not sure how to do it as cleanly as possible. There's also the fact that `pacman_command` does not behave like `makepkg_command` in that it allows for base flags. I was tempted at first to add `pacman_command  => "/usr/bin/pacman --root=/srv/archbuild/chroot64/root"` but it tries to execute it as one command.

**Comment by trizen** [comment]
Hi,

Good catch! Thanks for reporting this.

Fixed in the previous [commit](https://github.com/trizen/trizen/commit/d5226a676f89a84737f69fd7128d63c42482b507) by using `$lconfig{pacman_command}` instead of `/usr/bin/pacman`.

Also fixed the executed of the `pacman_command` to behave like the `makepkg_command`, which allows a user to specify the `pacman_command` as command-line argument, with optional arguments, such as:

```
trizen -S <package> --pacman-command="pacman --root=/srv/archbuild/chroot64/root"
```

The leftover arguments are not yet passed to each internal pacman invocation, because this will likely product wrong results in some edge cases.

**Comment by popsUlfr** [comment]
Very nice! Combining trizen with [clean-chroot-manager](https://github.com/graysky2/clean-chroot-manager) gives a AUR powerhouse with distcc support.

```sh
$ trizen --pacman_command="/usr/bin/pacman --root=/srv/archbuild/chroot64/root" --pacman_local_dir="/srv/archbuild/chroot64/root/var/lib/pacman/local" --makepkg_command="/usr/bin/sudo /usr/bin/ccm64 s" -S --noedit --noinstall --needed ffmpeg-full
```

> The leftover arguments are not yet passed to each internal pacman invocation, because this would likely produce wrong results in some edge cases.

But that's the user's responsibility then if they decide to mess with the pacman command :thinking: .  One can already do some weird stuff anywhere the `execute_pacman_command()` is used I guess.

**Comment by trizen** [comment]
That's awesome! I suppose `--pacman-command="..."` is enough for most purposes, then.
