### ISSUE TITLE
Option to sort AUR package search results

### ISSUE THREAD

**Issue by mklein994** [trizen/trizen#58]
This is a feature request. Here's what I had in mind:

Let's say this is my configuration file:
```perl
our $CONFIG = {
    # …
    aur_results_sort => 'Popularity',
    # …
}
```

When I search a package, the results listed could be sorted by popularity. The same could be configured to be sorted by number of votes, package name, date the package was last updated, and so on.

**Comment by trizen** [comment]
Hi. Thank you for suggesting this nice feature request. 

It has successfully been implemented [here](https://github.com/trizen/trizen/commit/b170222663fa8a83423218edb040d498d5c0b11c), along with two new configuration options:

```perl
aur_results_sort_by    => "name",      # valid values: "name", "votes", "popularity" and "date"
aur_results_sort_order => "ascending", # valid values: "ascending" or "descending"
```

The configuration options are also available as command-line arguments:

```console
 trizen -Ss geany --aur-results-sort-by=date --aur-results-sort-order=descending
```

**Comment by btd1337** [comment]
Is It possible to set an default setting for the result sort and sort order?

**Comment by trizen** [comment]
Yes, by editing the configuration file.

**Comment by btd1337** [comment]
@trizen where is this file?
