### ISSUE TITLE
Feature Request: Option to only use the regular repositories

### ISSUE THREAD

**Issue by physkets** [trizen/trizen#60]
`pacaur -r` was the equivalent of `pacman`, and enabled its use as a complete pacman replacement, because commands like `-Ss` are otherwise annoying if you only want to look in the official repos.

**Comment by trizen** [comment]
Thanks for the suggestion. Implemented [here](https://github.com/trizen/trizen/commit/ec56401d89a4b12ebeafef571b6ab53dc0440253).
