### ISSUE TITLE
Feature Request: verification of diff outputs of already installed/verified AUR packages

### ISSUE THREAD

**Issue by chrpinedo** [trizen/trizen#63]
The first time is quite useful to show and verify the full content of the PKGBUILD and additional files prior to installation. However, once installed the AUR package IMHO it is more appropiate/comfortable to show only the diff of previously accepted PKGBUILD and additional files. 

This is the normal behaviour of pacaur and it was really useful.

Kind regards!

**Comment by AladW** [comment]
https://github.com/trizen/trizen/commit/536caceaeabb3b977bf077c402bbf87464d54b0c

**Comment by chrpinedo** [comment]
I will check it in the next AUR release!

**Comment by trizen** [comment]
This feature is now available in version 1.39.
