### ISSUE TITLE
Feature: Allow to customize colors

### ISSUE THREAD

**Issue by lervag** [trizen/trizen#66]
For some reason, one of the colors used by trizen looks strange. I use urxvt with solarized colors, and a bold yellow color has an altered and out-of-place background color, see screenshot below.

![screen](https://user-images.githubusercontent.com/998898/34561179-13cddf34-f149-11e7-8198-a8a1aa4b657d.png)

If I could customize the colors on my end, then I could fix this problem myself.

**Comment by lervag** [comment]
I've noticed this part:

```perl
my %c = (
         cblack  => (ON_BLACK),
         byellow => (BOLD YELLOW),
         bpurple => (BOLD MAGENTA),
         bblue   => (BOLD BLUE),
         bgreen  => (BOLD GREEN),
         bbgreen => (BOLD GREEN ON_BLACK),
         bold    => (BOLD),
         bred    => (BOLD RED),
         reset   => (RESET),
        );
```

I was wondering if you could either remove the `ON_BLACK` stuff, which I personally can't understand why you want to add here, or allow the config file to override these colors somehow.

**Comment by lervag** [comment]
Basically, it seems it should be enough to change `my %c` to `our %c`?

**Comment by trizen** [comment]
Hi,

The idea behind `ON_BLACK` was to make the green and yellow colors more readable on a terminal with a white background, but I guess not many people use `xterm` with default settings anyway, so removing this should be fine.

Thanks for reporting.

**Comment by lervag** [comment]
Thanks for the info and for the quick fix. I'm happy you agreed with my suggestion!
