### ISSUE TITLE
support git clones

### ISSUE THREAD

**Issue by AladW** [trizen/trizen#7]
AUR4 added the ability to clone AUR packages via git. This allows amongst others to easily view maintainer changes in the pkgbuild. Right now ``trizen`` only supports the old tar interface.

https://lists.archlinux.org/pipermail/aur-dev/2015-August/003697.html

**Comment by trizen** [comment]
The support for git clones is ready for testing.

**Comment by AladW** [comment]
Thanks, for me files are retrieved correctly on `trizen -S`. A question, is there a particular reason you're only fetching the latest commit (i.e., `git log` only displays one entry) ?

**Comment by trizen** [comment]
Thanks for the suggestion. There is no particular reason, other than a potential speed improvement for packages with many commits.

However, this is now configurable with the `git_clone_depth` config-option. By default, the value is 0, which means no limit.

**Comment by AladW** [comment]
Thanks!
