### ISSUE TITLE
Feature Request: option for disable ask-for-retry

### ISSUE THREAD

**Issue by hxss** [trizen/trizen#70]
I think, this is unnecessary interaction with the user. And this 2 questions ask the same thing, but expect different answers for same action(exit).
```
[...] makepkg exited with code: 1
=>> Do you want to try again? [y/N]: n
=>> Do you want to exit now? [Y/n]: y
```
It will be great if I can disable this questions in trizen.conf

**Comment by trizen** [comment]
Hi. Thank you for the suggestion.

The `ask_for_retry` config-option has been added [here](https://github.com/trizen/trizen/commit/3d517efb0682c970f7be2b3576b8f7522929ed83) (enabled by default).

The questions that it asks look fairly similar, but are actually two different questions:

1. Do you want to try again?
  - if "y", then will try to build the package again, offering to optionally edit the PKGBUILD
  - if "n", then will ask the second question

2. Do you want to exit now?
  - if "y", then will exit the program immediately
  - if "n", then will just skip this package and continue with the other packages (if any)

This questions can now also be disabled with the `--ask-for-retry=0` argument:
```console
trizen --ask-for-retry=0 -S <package>
```
