### ISSUE TITLE
Issue with depencendy for a split package

### ISSUE THREAD

**Issue by jendrikw** [trizen/trizen#72]
I'm trying to install clion (https://aur.archlinux.org/pkgbase/clion/), which is part of a split package. Another part, `clion-lldb` declares a dependency on `ncurses5-compat-libs`, which trizen is forcing me to install. I don't want this as clion doesn't have the dependency.

**Comment by AladW** [comment]
Trizen should indeed not install local (specified in a split package) depends; from `PKGBUILD(5)`:

>Note that makepkg does not consider split package depends when checking if dependencies are installed before package building and with --syncdeps. All packages required to make the package are required to be specified in the global depends and makedepends arrays.
