### ISSUE TITLE
Man page

### ISSUE THREAD

**Issue by SolidTux** [trizen/trizen#74]
Having a man page would be handy, especially for fish users as then the completion would work.

Is there a possibility to generate the man page as the information is already available as help output?

**Comment by japhir** [comment]
I agree! I tried to figure out where to specify the package cache is defined, so that I could change it for one very big package that doesn't fit on my /tmp. Getting a "No manual entry for trizen" is disheartening!

PS: It worked by specifying BUILDDIR in ~/.config/pacman/makepkg.conf

**Comment by mjtullio** [comment]
I agree. Fish completion would be nice to have.

**Comment by bulletmark** [comment]
I would suggest that have a man page is not just "handy".  All respectable Linux packages should have a man page. I installed `trizen` then typed `man trizen` to find it missing and so was immediately put off. Then installed `yay` and found that `man yay` works.

**Comment by MarcusE1W** [comment]
I had a look what is actually required to create man pages. Seems it is quite possible to create a man page from a markdown page.
For a test I have directly converted the trizen README into the man format using `pandoc`.
The command for that is:
```
pandoc README.md -s -f gfm -t man -o trizen.1
```
I have written a short tutorial [here](https://absolute-beginner.netlify.com/post/man-markdown/)

The result can be found in this [gist](https://gist.github.com/MarcusE1W/cab092d1443bba6950c2136844f68e61).

to see a preview use `man -l trizen.1`

The normal man pages have a different standard format than the current README file has, but I guess it would not be not be too much effort to add a few headers.

What I don't know yet is how a man page has to be installed in the system to be found. 

to be continued...

**Comment by Hritik14** [comment]
@japhir  I came across the same issue. Turns out, you don't have to mess with pacman config. Just use `--clone-dir`

**Comment by bulletmark** [comment]
@MarcusE1W that is klnd of irrelevant to this issue which is about the lack of a man page. @japhir only mentioned his issue as an example of information he was hoping to find. BTW, Setting `clone_dir` in your `~/.config/trizen/trizen.conf` is the best way to set that once and for all. Yet another thing we could all easily find out about if there was a man page!

**Comment by MarcusE1W** [comment]
@bulletmark Good we agree that this issue is about the lack of a man page for Trizen. 
My comment intended to show a way to create a Trizen man page from the already existing documentation as a reply to the original question.

**Comment by bulletmark** [comment]
Sorry @MarcusE1W, my reply was intended for @Hritik14, somehow I messed up the attribution which I just edited to correct.
