### ISSUE TITLE
Feature Request: Env variables & relative paths in config?

### ISSUE THREAD

**Issue by hxss** [trizen/trizen#75]
It would be convenient to be able to specify relative paths in the config.
For example I need to specify `clone_dir` as `~/.cache/trizen`.

Now I can only use workaround like this:
```
my $home = `echo -n \$HOME`;

our $CONFIG = {
  ...
  clone_dir                    => "$home/.cache/trizen",      #   str -- Absolute path to the directory where to clone and build packages.
  ...
}
```

**Comment by trizen** [comment]
For the home directory, you can use `$ENV{HOME}`, as:

```perl
clone_dir => "$ENV{HOME}/.cache/trizen",
```
