### ISSUE TITLE
Cannot build GZDoom

### ISSUE THREAD

**Issue by s0r00t** [trizen/trizen#76]
[The package is available here.](https://aur.archlinux.org/packages/gzdoom/)
```
fatal: 'g3.2.5' is not a commit and a branch 'makepkg' cannot be created from it
==> ERROR: Failure while creating working copy of gzdoom git repo
```

There seems to be an error when parsing the PKGBUILD.

**Comment by aveao** [comment]
CNR, [full build asciinema here](https://asciinema.org/a/pzpalVf80F1X7c2fQUtIPIJG8).

**Comment by trizen** [comment]
As illustrated by @aveao, the package seems to build without problems. Probably just trying again would solve the issue.

**Comment by s0r00t** [comment]
I tried several times before opening the issue. It is still occuring.

**Comment by s0r00t** [comment]
Cleaning the cache & recloning the repo seems to work. Either way, such an issue shouldn't occur when updating a package whose repo is present in the cache.

**Comment by trizen** [comment]
Maybe it's a `git` or a `makepkg` issue?
