### ISSUE TITLE
Package attempting to update on every update

### ISSUE THREAD

**Issue by SilverMight** [trizen/trizen#77]
A package I have installed, specifically `kshare-git` is attempting to update everytime I run trizen -Syu on my PC. This update does not display on any other AUR helper (pacaur, yay, etc.)
`1. kshare-git: v4.1.234.g785400b-1 ==> v4.1.r196.gc38161b-1` is what Trizen outputs - after updating it still shows that it needs to be updated after running trizen -Syu again.

Pacaur, yay, and yaourt does not display this update.

**Comment by X0rg** [comment]
Pacaur clone package repository into `~/.cache/pacaur`, and leave source files into this directory.

One idea to fix this issue in trizen:
1. In `~/.config/trizen/trizen.conf`, change `clone_dir` value to `~/.cache/trizen`.
2. `BUILDDIR` environment variable must be set properly before calling `makepkg`.
3. Reuse package directory if exists, else clone.

**Comment by coderobe** [comment]
This should be fixed with https://github.com/trizen/trizen/commit/3ef9adba7e39fe2b5e4b989d3268a6226f6fdc16

**Comment by SilverMight** [comment]
Yup, seems to work fine now. Closing.
