### ISSUE TITLE
ability to download packages and their dependencies without building

### ISSUE THREAD

**Issue by AladW** [trizen/trizen#8]
When a chain of packages is built, either a prompt is displayed to view each PKGBUILD and assorted files, or the package is built without confirmation using `trizen --noconfirm`. With long chains of packages (e.g. `plasma-desktop-git`, `ros-indigo-desktop`), this means you either have to confirm a few hundred PKGBUILDs, spread over a lenghty build process, or hope for the best and not inspect files at all.

A workaround could be to extend the `-G` operation to also fetch dependencies. Then the user can inspect the files manually (e.g. using a file manager of choice) and run `trizen` again, possibly reusing the existing build files.

**Comment by trizen** [comment]
Nice feature request!

This is now supported by the `-Gd` option.

```console
% trizen -Gd sidef-git
```
After the inspection of build files, the user can run:

```console
% trizen --clone_dir=. --nopull -S sidef-git 
```
The `--nopull` option is useful when the user edits the build files.

**Comment by AladW** [comment]
I've tried it with `plasma-desktop-git` and it works as intended. :+1: Cheers
