### ISSUE TITLE
How to change the default editor

### ISSUE THREAD

**Issue by stokhos** [trizen/trizen#81]
Hi:

Is there a way to change the default editor from nano to neovim?

Best

**Comment by aveao** [comment]
Try setting $EDITOR in .bashrc/.zshrc/.fishrc to nvim.

On January 13, 2018 9:15:46 AM GMT+03:00, Stokhos <notifications@github.com> wrote:
>

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stokhos** [comment]
@aveao It works! Thank you!
