### ISSUE TITLE
trizen -Syu looks at AUR for packages that are official repos

### ISSUE THREAD

**Issue by stokhos** [trizen/trizen#84]
After run trizen -Syu, Some time I meet this problem. 
trizen -Syyu fixes this problem
but this problem keep showing up later.

I'm using pacman with aria2c, with pacman

(11/11) upgrading virtualbox-sdk                   [#####################] 100%
:: Running post-transaction hooks...
(1/7) Updating linux module dependencies...
(2/7) Registering Haskell modules...
(3/7) Updating icon theme caches...
(4/7) Updating system user accounts...
(5/7) Arming ConditionNeedsUpdate...
(6/7) Updating the desktop file MIME type cache...
(7/7) Updating the MIME type database...
error: could not parse package description file 'xorg-xprop-1.2.2-1/desc' from db 'extra'
:: Package xorg-xrdb was not found in AUR -- skipping
:: Package xorg-xset was not found in AUR -- skipping
:: Package xproto was not found in AUR -- skipping
:: Package xvidcore was not found in AUR -- skipping
:: Package yajl was not found in AUR -- skipping
:: Package zenity was not found in AUR -- skipping
:: Package zip was not found in AUR -- skipping
:: Package zita-alsa-pcmi was not found in AUR -- skipping
:: Package zita-resampler was not found in AUR -- skipping
:: Package zvbi was not found in AUR -- skipping
:: Package zziplib was not found in AUR -- skipping
:: No AUR updates found...

**Comment by trizen** [comment]
```
error: could not parse package description file 'xorg-xprop-1.2.2-1/desc' from db 'extra'
```

There seems to be something wrong with the description of `xorg-xprop`, which confuses pacman. Maybe reinstalling this package would solve the issue.

**Comment by stokhos** [comment]
Hey, Im still having this problem. 
I didn't install xorg-xprop.
and then i thought maybe install it would solve the problem. After I installed it. I'm still having the same problem, and this time, it changes to another package.

**Comment by trizen** [comment]
If you think this is not a local issue, you may want to report this to the pacman developers, as the errors comes from pacman, not from trizen.
