### ISSUE TITLE
provide an error message on unfound target

### ISSUE THREAD

**Issue by AladW** [trizen/trizen#9]
If a target is not found, trizen exits quietly with a zero exit status.
```
[archie@bootstrap ~]$ trizen -S foodoesnotexist
[archie@bootstrap ~]$ echo $?
0
```
Compare to pacman:
```
[archie@bootstrap ~]$ sudo pacman -S foodoesnotexist
error: target not found: foodoesnotexist
[archie@bootstrap ~]$ echo $? 
1
```
The `-G` operation is similar.
```
[archie@bootstrap ~]$ trizen -G foodoesnotexist
[archie@bootstrap ~]$ echo $?
0
```

**Comment by trizen** [comment]
The exit-code on a failure is now set appropriately to a non-zero value.

For `-S` a warning message still needs to be added, but the exit-code is no longer zero.
```console
% trizen -S foodoesnotexist
% echo $?
1
```

For `-Si`, `-Sp`, `-G` and `-U` a warning message is displayed correspondingly:

```console
% trizen -Si foodoesnotexist
warning: package not found: foodoesnotexist
% echo $?
1
```

```console
% trizen -Sp foodoesnotexist
warning: package not found: foodoesnotexist
% echo $?
1
```

```console
% trizen -G foodoesnotexist
warning: package not found: foodoesnotexist
% echo $?
1
```

```console
% trizen -U foodoesnotexist
warning: local package not found: foodoesnotexist
% echo $?
2
```
Thank you for reporting this!

**Comment by trizen** [comment]
This issue is now completely fixed in [this commit](https://github.com/trizen/trizen/commit/5b02e394b85b45dac3a48381eea08f71844fd577). A warning message is produced for each failure and an appropriate exit-code is set correspondingly.
