### ISSUE TITLE
ZSH Completions doesn't work

### ISSUE THREAD

**Issue by bugworm** [trizen/trizen#90]
![image](https://user-images.githubusercontent.com/7214361/35241936-d03d5a0c-ffc0-11e7-975f-12f8f240cca1.png)

**Comment by trizen** [comment]
It's a local issue. Try adding the following lines in `~/.zshrc`:

```bash
zmodload zsh/complist
autoload -Uz compinit
zstyle ':completion:*' matcher-list '' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
```

See also: https://wiki.archlinux.org/index.php/Zsh#Command_completion

**Comment by bugworm** [comment]
Strange that it was working fine on any other app all this time. Well, thanks anyway
