### ISSUE TITLE
[Suggestion] Batch repository installs

### ISSUE THREAD

**Issue by gourdcaptain** [trizen/trizen#93]
If I try a "pacman -S package1 package2" where both packages are in the repositories, it asks me to install both at once with one prompt. If I try that with trizen ("trizen -S package1 package2"), it asks me to install one then asks to install the other. Would it be possible to have it batch up repository installs to reduce the number of prompts? 

(Will add that I switched to Trizen after pacaur got discontinued, and while it's not quite the same experience, it's pretty good at doing everything I need it to, so thanks. :) )

**Comment by aveao** [comment]
This is by design (see comment by trizen on #46), though I have to say that it's quite annoying.

On January 24, 2018 2:47:07 AM GMT+03:00, gourdcaptain <notifications@github.com> wrote:
>

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
