### ISSUE TITLE
--needed sees a higher sha-only pkgver as an upgrade

### ISSUE THREAD

**Issue by milkmiruku** [trizen/trizen#94]
Some -git packages have pkgver() that just uses the commit sha, e.g., dmenu-ee-git, ganv-git.

`trizen -Syu --noconfirm --noedit --needed` reports the "higher" sha as being an upgrade. 

```
 1.         dmenu-ee-git:                  e411552-1 ==> fca1ce9-1
...
 4.             ganv-git:                  dc3db77-1 ==> e7731e9-1
```

(In this instance dmenu-ee-git AUR PKGBUILD has fca1ce9-1, but when cloned trizen gets e411552-1, builds it then doesn't install it, but that's another issue.)

I'm not sure if this can be mitigated in the AUR helper? The PKGBUILDs could certainly have a more appropriate pkgver. I'm wondering what packages are the reverse (and thus not seen for upgrade).

**Comment by milkmiruku** [comment]
from #archlinux-aur :)
```
<milk> Some -git packages have pkgver() that just uses the commit sha, e.g., dmenu-ee-git, ganv-git. This makes AUR helper trizen think a higher sha is an upgrade. Is it the AUR helpers responsibility to mitigate this, or more the issue of the PKGBUILD (or why not both)?
<guys> It is the PKGBUILD's fault for being moronic. :p
<louipc> tru
<guys> We have a very nice wiki detailing exactly how to use pkgver()
<guys> https://wiki.archlinux.org/index.php/VCS_package_guidelines#Git
<phrik> Title: VCS package guidelines - ArchWiki (at wiki.archlinux.org)
<louipc> or is it PKGBUILD fault for allowing PKGBUILDs to be moronic
<guys> louipc: I challenge you to discover a technical solution to this...
<louipc> end the human race
<milk> hahah
```

**Comment by GUiHKX** [comment]
This is a new one to me, lol. I think the appropriate thing to do is ask the maintainers of said packages to do proper versioning. If they take too long to answer, submit a request to orphan said package. After your request is accepted, you could simply become the owner and fix it yourself. I don't think there's much trizen can do...

**Comment by trizen** [comment]
I agree with @GUiHKX. The versioning should be fixed by the maintainers of this packages.
